### ISSUE TITLE
Set default credentials

### ISSUE THREAD

**Issue by LittleColin** [reportportal/kubernetes#104]
A question rather than an issue, what is the recommendation on setting default passwords for superadmin and default? Is it possible to supply these in the helm chart values? Or call an API to reset them? Or create new users and disable these accounts?

**Comment by AlehB** [comment]
Hi @LittleColin ,

**Comment by AlehB** [comment]
Hi @LittleColin ,

Please address such question in our Slack chanel or sent a mail to support@reportportal.io. More contacts - https://reportportal.io/community. This is not a kuberntes helm issue.

In general, default users are stored in database, therefore it cannot be changed via helm chart values

Best Regards,
Aleh
