### ISSUE TITLE
Service Analyzer and ES | Analyzer can't connect to a cloud ES when it's a https

### ISSUE THREAD

**Issue by jonathancarvalheiro** [reportportal/kubernetes#106]
We are using an external ES, with https instead of http.

When we tried to use the analyzer we had an error log :
![image](https://user-images.githubusercontent.com/57483006/77096603-7779ae80-6a07-11ea-8c5e-425ad2baa2fc.png)

So a solution was to replace the http -> https on analyzer-statefulset.yaml

![image](https://user-images.githubusercontent.com/57483006/76879660-77927680-686e-11ea-99ef-ef6a42637e0d.png)

But I think should be a better way to allow the use the http or https without changing the template.

**Comment by DzmitryHumianiuk** [comment]
@AlehB
