### ISSUE TITLE
ReportPortal -- AWS S3 to replace MinIO

### ISSUE THREAD

**Issue by thunder-spb** [reportportal/kubernetes#114]
Hey guys,

I have couple questions.
1. Is there any examples on how to use S3 instead of MinIO? Like what permissions should have User/Role to make it work.
2. Is it possible to use IAM Role based access (we use kube2iam service) for this? Or it's only with keys?

**Comment by HardNorth** [comment]
We introduced MinIO to have single interface, so no, you cannot use S3 instead of MinIO. But you can configure MinIO as S3 proxy, please refer its official documentation: https://github.com/minio/minio/blob/master/docs/gateway/s3.md

**Comment by Mahesh81** [comment]
> Hey guys,
> 
> I have couple questions.
> 
> 1. Is there any examples on how to use S3 instead of MinIO? Like what permissions should have User/Role to make it work.
> 2. Is it possible to use IAM Role based access (we use kube2iam service) for this? Or it's only with keys?


Hi

Can you let me know how you configured usin iam role. Do you still need secret and access key

Thanks
MaheshKumar

**Comment by Mahesh81** [comment]
> > Hey guys,
> > I have couple questions.
> > 
> > 1. Is there any examples on how to use S3 instead of MinIO? Like what permissions should have User/Role to make it work.
> > 2. Is it possible to use IAM Role based access (we use kube2iam service) for this? Or it's only with keys?
> 
> Hi
> 
> Can you let me know how you configured usin iam role. Do you still need secret and access key
> 
> Thanks
> MaheshKumar

@thunder-spb
