### ISSUE TITLE
Wrong indent for nodeSelector

### ISSUE THREAD

**Issue by timofeevvr** [reportportal/kubernetes#125]
Templates files has wrong indent for `nodeSelector` field in reportportal v5
`{{ include "nodeSelector" . | indent 8 }}`

With `indent=8` I got an error:
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "nodeSelector" in io.k8s.api.core.v1.Container`

Changing to `indent=8` helped

**Comment by timofeevvr** [comment]
I faced with odd behavior even after changing indent.
I've tried to add my own node selector in values.yaml during upgrade
```yaml
nodeSelector:
  enabled: true
  selector:
    Type: SystemNodeGroup
```
and got an error
```
Error: UPGRADE FAILED: cannot patch "reportportal-api" with kind Deployment: 
v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: 
v1.PodSpec.NodeSelector: ReadString: expects " or n, but found t, error found in #10 byte of ...|tportal":true},"rest|...,
 bigger context ...|lector":{"Type":"SystemNodeGroup","reportportal":true},"restartPolicy":"Always","schedulerName":"def|... 
&& cannot patch "reportportal-index" with kind Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: 
v1.PodSpec.NodeSelector: ReadString: 
expects " or n, but found t, error found in #10 byte of ...|tportal":true},"rest|..., bigger context ...|lector":
{"Type":"SystemNodeGroup","reportportal":true},"restartPolicy":"Always","schedulerName":"def|... 
&& cannot patch "reportportal-uat" with kind Deployment: v1.Deployment.Spec: 
v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadString: expects " or n, but found t, error found in #10 byte of ...|tportal":true},
"rest|..., bigger context ...|lector":
{"Type":"SystemNodeGroup","reportportal":true},"restartPolicy":"Always","schedulerName":"def|... 
&& cannot patch "reportportal-ui" with kind Deployment: v1.Deployment.Spec: 
v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadString: 
expects " or n, but found t, error found in #10 byte of ...|tportal":true},"rest|..., bigger context ...|lector":
{"Type":"SystemNodeGroup","reportportal":true},"restartPolicy":"Always","schedulerName":"def|... 
&& cannot patch "reportportal-analyzer" with kind StatefulSet: v1.StatefulSet.Spec: 
v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadString: 
expects " or n, but found t, error found in #10 byte of ...|tportal":true},"rest|..., bigger context ...|lector":
{"Type":"SystemNodeGroup","reportportal":true},"restartPolicy":"Always","schedulerName":"def|... 
&& cannot patch "reportportal-migrations" with kind Job: v1.Job.Spec: v1.JobSpec.Template: 
v1.PodTemplateSpec.Spec: v1.PodSpec.NodeSelector: ReadString: expects " or n, but found t, error 
found in #10 byte of ...|tportal":true},"rest|..., bigger context ...|lector":
{"Type":"SystemNodeGroup","reportportal":true},"restartPolicy":"Never","schedulerName":"defa|...
```

So I've edited templates to have this:
```yaml
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
```
And chart values field like this:
```yaml
nodeSelector: {}
#  reportportal: true
```
Only after these changes, I was able able to upgrade my release.

**Comment by Cyberglamdring** [comment]
Hello @timofeevvr , which version of Kubernetes are you using?

**Comment by eric-engberg** [comment]
I'm getting this error when trying to use chart version 5.4.0.

The helm chart currently indents nodeSelector under spec.template.spec.containers[x].nodeSelector
This is however incorrect as nodeSelector isn't at the container level but the pod level.  Should be spec.template.spec.nodeSelector

**Comment by HardNorth** [comment]
@timofeevvr We have a straight requirement of K8S version >= 1.16, and we are not going to support older versions.
Please see: https://github.com/reportportal/kubernetes#requirements

**Comment by eric-engberg** [comment]
This is not a <1.16 version issue.  I am on 1.22 and encounter the same thing

**Comment by HardNorth** [comment]
@eric-engberg Can you please provide more details? What exactly you've done to get the error? We do installs and updates on dayly basis and don't see such errors.

**Comment by HardNorth** [comment]
@eric-engberg OK, found the issue. Unfortunately I haven't found a way to fix it without breaking changes, so now it work differently, see comments section in `values.yaml`: https://github.com/reportportal/kubernetes/blob/develop/reportportal/values.yaml#L246

The changes will be pushed into `master` and release with the new version of RP.
