### ISSUE TITLE
Which version of Kubernetes is needed?

### ISSUE THREAD

**Issue by guettli** [reportportal/kubernetes#140]
In the README.md:

> Kubernetes =<1.14

What does this mean?

According to helm char comparison: https://helm.sh/docs/chart_template_guide/function_list/#basic-comparisons

it should be `<=` if you mean "less or equal".

I am a bit confused, since in most cases "greater or equal" gets used. But if I read like "1.4" or smaller version.

I run `minikube start --driver=docker` with version 1.19.

**Comment by Cyberglamdring** [comment]
Hello,
At now Reportportal supported Kubernetes up to 1.15.  We update the documentation to Kubernetes v 1.16+ as soon as it possible.

**Comment by deepaleekhare31** [comment]
@Cyberglamdring Can report portal be installed in cluster with Kubernetes version: 1.19.9?

**Comment by Cyberglamdring** [comment]
@deepaleekhare31, we tested on v1.19.8. Works great.
