### ISSUE TITLE
mv v5 reportportal .... grrr

### ISSUE THREAD

**Issue by guettli** [reportportal/kubernetes#142]
According to the docs you should rename the directory "v5" to "reportportal". 

This is a bit annoying since you can easily create pull request, since the path of all files in this directory have changed.

It would be cool, if you could find a way to get it working without a "mv".

For example like this: Create a directory in v5:

v5/reportportal/

**Comment by Cyberglamdring** [comment]
Dear @guettli, we plan to update and structure the documentation soon. We will also add support for Kubernetes version 1.16+.
