### ISSUE TITLE
Support for Kustomize?

### ISSUE THREAD

**Issue by mide1234** [reportportal/kubernetes#154]
Hi,

is there any chance that Report Portal will support deployment via [Kustomize](https://kustomize.io/)?

Has anyone tried to spin up Report Portal via Kustomize?

Thanks

**Comment by englandprevails** [comment]
Answering your second question, I found Kustomize to take the place of specifying only the _modifications and alterations_ of the charts which come from upstream.  In our workflow, we use the Helm chart(s) to create the resource definitions, and only maintain the Kustomize patches for modifying those resource definitions to suite our environment.
Each environment thus requires its own custom Kustomize patches.
For a full Kustomize-based deployment, I also wonder if the maintainers might entertain a PR, to avoid a hybrid solution which requires Helm too.

**Comment by jbadeau** [comment]
I dont' see an issue with helm. We currently install reportportal using [helmfile](https://github.com/roboll/helmfile#highlights).
We utilize the helmfile builtin JSON/Strategic-Merge Patch Kubernetes resources before helm-installing, without forking upstream charts. It works great.

**Comment by HardNorth** [comment]
@mide1234 There is no such plans. And unfortunately we don't have capacity to support yet another deployment tool, so I believe we can close the issue until better times.
