### ISSUE TITLE
Having an issue with installing reportportal using helm.

### ISSUE THREAD

**Issue by zozo6015** [reportportal/kubernetes#170]
I have tried installing reportportal using Helm all dependencies are installed then I actually installing the reportportal helm chart from local package I am getting the following error message:

```
helm install reportportal -n testing --set postgresql.SecretName=postgresql,rabbitmq.SecretName=rabbitmq ./reportportal-5.3.5.tgz
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodDisruptionBudget "elasticsearch-master-pdb" in namespace "testing" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "reportportal": current value is "elasticsearch"
```
Anyone have any idea what is this error message about and how to fix it?

**Comment by ghalkouski** [comment]
@Cyberglamdring can you please a look here?

**Comment by HardNorth** [comment]
@zozo6015 @ghalkouski I can't really reproduce this error. I deployed RP many times in July and haven't seen such error. My best guess is that you guys unpacked another chart into the same folder. If so, that's incorrect.
