### ISSUE TITLE
Error: must either provide a name or specify --generate-name

### ISSUE THREAD

**Issue by patsevanton** [reportportal/kubernetes#176]
Hello! I try to install reportportalinto kubernetes by helm

**helm version**
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

**helm repo add stable https://charts.helm.sh/stable && helm repo update**
"stable" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈

**helm repo list**
NAME    URL                          
stable  https://charts.helm.sh/stable

**helm install ./reportportal/**
Error: must either provide a name or specify --generate-name

Can i fix documentation ?

**Comment by cnolick** [comment]
try this helm install reportportal ./reportportal

**Comment by patsevanton** [comment]
This issue about helm2/helm3
