### ISSUE TITLE
Documentation issue for RabbitMQ and Postgres via helm

### ISSUE THREAD

**Issue by TonyNoble** [reportportal/kubernetes#186]
Documentation is incorrect / inadequate for installing RabbitMQ and MinIO, regarding authentication

# RabbitMQ
Documentation suggests the command to install via helm is:
```
helm install <rabbitmq_chart_name> --set auth.username=rabbitmq,auth.password=<rmq_password>,replicaCount=1 ./reportportal/charts/rabbitmq-7.5.6.tgz
```
However, in the rabbitmq values file, default_pass is hard-coded to 'CHANGEME' and cannot be overridden.  Workaround is to port-forward to gain access to the UI and set the password from there.

# Postgres
The first scripts in the database migration job involve creating extensions.  However, this is attempted as the report portal user rather than the postgres user, which does not have permission to do this.  Workaround is to temporarily grant the report portal user superuser permissions

**Comment by HardNorth** [comment]
@TonyNoble You are saying something that completely agains my experience. I deployed RP from scratch several times on two weeks ago using these commands and everything was fine, including rabbit password and postgres user. Please ensure you are using exact charts, which we put in `requirements.yaml`.

**Comment by HardNorth** [comment]
@TonyNoble For example, rabbit:
https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#global-parameters
Has described parameter "auth.password" which we use:

Name | Description | Value
-- | -- | --
auth.password | RabbitMQ application password | ""

And it's **not hardcoded** to "CHANGEME":
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L104

**Comment by TonyNoble** [comment]
@HardNorth 

Please read further down the *very same file* that you linked to.  In the generated rabbitmq.conf configmap, the "default_pass" item is set to "CHANGEME".  I have just repeated the install as described in the reportportal readme:

Command run (unzipped the archive because I needed to add limits to the values file and turn off clustering):
```
helm install rabbitmq --set auth.username=rabbitmq,auth.password=rabbitmq,replicaCount=1 ./rabbitmq -n default
```

Now in kubernetes:
```
$ kubectl get -n default configmap
NAME              DATA   AGE
rabbitmq-config   1      14m
```

followed by:
```
$ kubectl get -n default configmap rabbitmq-config -o yaml
apiVersion: v1
data:
  rabbitmq.conf: |-
    ## Username and password
    default_user = rabbitmq
    default_pass = CHANGEME
    ## Clustering
    #cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    #cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    #cluster_formation.node_cleanup.interval = 10
    #cluster_formation.node_cleanup.only_log_warning = true
    #cluster_partition_handling = autoheal
    # queue master locator
    queue_master_locator = min-masters
    # enable guest user
    loopback_users.guest = false
    #disk_free_limit.absolute = 50MB
    #management.load_definitions = /app/load_definition.json
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: rabbitmq
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-30T11:19:05Z"
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-7.5.6
  name: rabbitmq-config
  namespace: default
  resourceVersion: "107220708"
  selfLink: /api/v1/namespaces/default/configmaps/rabbitmq-config
  uid: f34b6361-f127-11eb-b22c-0050569a41a2
```

Please note the default_pass entry there as I mentioned.  When I connect the UI of rabbitmq once the deployment is complete, these are the only credentials I am able to connect with.

**Comment by HardNorth** [comment]
@TonyNoble Yep, noe I see this. But I double-checked and I do have this "CHANGEME" "password" in my configmap. But it not affects my deployment.

It's because the chart creates a secret with password here:
https://github.com/bitnami/charts/blob/c2651190070d861f592b35fd08c4de22f10c84be/bitnami/rabbitmq/templates/secrets.yaml

And then use the secret instead of configmap, which is pretty smart, since configmaps are open and secrets are not:
https://github.com/bitnami/charts/blob/c2651190070d861f592b35fd08c4de22f10c84be/bitnami/rabbitmq/templates/statefulset.yaml#L159

So no hardcoded / opened password anyway. So if your rabbit picks up "CHANGEME" password please ensure you are using correct chart version, there might be some bugs in different versions.

**Comment by TonyNoble** [comment]
@HardNorth 
Thanks for the clarification - I see RABBITMQ_PASSWORD set up as an environment variable in the pod and containing the correct value pulled from the secret, but it seems rabbitmq didn't use it on initial startup and referenced the config file instead.

The charts were retrieved by running `helm dependency build ./reportportal` and then unzipping the result (rabbitmq-7.5.6.tgz) and modifying the values file as required by our k8s setup.  It's odd that it's happened twice to us - but I guess from what you've said, it's an issue with rabbitmq, if anywhere.

Regarding the postgres issue, I'll attempt to reproduce again if I can find some capacity to do it and either update or close this issue as appropriate.  My initial experience was that while the reportportal db and user were created, the report portal user did not have permission to install the required extensions, so the migration pods failed.
