### ISSUE TITLE
Minio using iam role

### ISSUE THREAD

**Issue by Mahesh81** [reportportal/kubernetes#189]
Hi
I am hosting report portal in eks and it's mentioned minio configuration needs iam user acess key. We are allowed to use iam role and access key is prohibited. Please provide alternative options to configure minio. 

Appreciate your help
Thanks
Mahesh
#reportportal

**Comment by HardNorth** [comment]
@Mahesh81 I can only refer to official minio documentation: https://github.com/minio/minio/blob/master/docs/gateway/s3.md
The documentation states that it's also possible.

Sorry, but we can't provide examples for every possible use case on earth.
