### ISSUE TITLE
missing required field "serviceName" in io.k8s.api.apps.v1beta2.StatefulSetSpec;

### ISSUE THREAD

**Issue by martcastaldo** [reportportal/kubernetes#2]
Hi,
I'm getting the following error running this on K8s:

Kubectl apply failed. Error: error: error validating "/tmp/app-template407551671": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1beta2.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false : exit status 1

Thanks,

Martin

**Comment by MaksymBilenko** [comment]
how did you try to install this one?
Have you used you own values.yaml?

**Comment by martcastaldo** [comment]
Nope, I thought that there was a default one?

**Comment by martcastaldo** [comment]
@MaksymBilenko Any pointers? :D

**Comment by avarabyeu** [comment]
Guys, i guess this can be closed since helm chart re-implemented. Please, open new one if problem still relevant
