### ISSUE TITLE
[v5] Unclassified Report Portal Error - when installing report portal 5.5.0 in EKS 1.18

### ISSUE THREAD

**Issue by arnikasky** [reportportal/kubernetes#206]
Describe the bug
When installing Report portal v5.5.0 in AWS EKS, reportportal-api pod is in state "CrashLoopBackOff" because of "Unclassified Report Portal Error".
report_portal.log

To Reproduce
AWS, EKS v1.18
Report Portal v5.5.0
elasticsearch, minio, postgres, rabbit are installed in this cluster too as pods.

Expected behavior
All pods of application work correctly.

Desktop (please complete the following information):
versions of deployments:
serviceindex:
tag: 5.0.10
uat:
tag: 5.5.0
serviceui:
tag: 5.5.0
serviceapi:
tag: 5.5.0
servicejobs:
tag: 5.5.0
migrations:
tag: 5.5.0
serviceanalyzer:
tag: 5.5.0
metricsgatherer:
tag: 1.1.14

**Comment by HardNorth** [comment]
I believe there is no EKS 1.18 dependency. Could you please collect logs from `reportportal-api` pod?

**Comment by arnikasky** [comment]
Sorry, forgot to add. Attached:
[report_portal.log](https://github.com/reportportal/kubernetes/files/7122576/report_portal.log)

**Comment by HardNorth** [comment]
It might be opaque message but if you look here: https://github.com/reportportal/service-api/blob/develop/src/main/java/com/epam/ta/reportportal/core/configs/rabbit/AnalyzerRabbitMqConfiguration.java#L56

You will se that it fails because of incorrect RabbitMq address. Please verify your RabbitMq address is valid.

**Comment by arnikasky** [comment]
Hello, thank you for quick answer!
I re-checked credentials using rabbitmqadmin and it works and credentials are correct true.
I believe, that it's not error  of rabbitmq, as in this case we should see additional  messages, like here: https://github.com/reportportal/service-api/search?q=Unclassified+Report+Portal+Error - "Unable to create RabbitMq virtual host" or like here: https://github.com/reportportal/service-api/blob/d16a30d3d4f6430c0fe45e3df2208dac7e21887e/src/main/java/com/epam/ta/reportportal/core/configs/rabbit/AnalyzerRabbitMqConfiguration.java - "Cannot create a HTTP rabbit client instance. Incorrect api address ".
I think, this error comes from these files: https://github.com/reportportal/service-api/blob/ae9c545acc97cf7e60005320c3c47fe13e623643/src/main/java/com/epam/ta/reportportal/demodata/service/DemoLogsService.java
or https://github.com/reportportal/service-api/blob/d16a30d3d4f6430c0fe45e3df2208dac7e21887e/src/main/java/com/epam/ta/reportportal/core/item/impl/provider/impl/MaterializedWidgetProviderHandlerImpl.java

**Comment by HardNorth** [comment]
@arnikasky please share your `kubectl get services` command results and rabbit section from `values.yaml`.

**Comment by arnikasky** [comment]
Hello @HardNorth 
Services:

➜ kubectl get services rabbitmq-headless rabbitmq postgres-postgresql-headless postgres-postgresql postgres-exporter-prometheus-postgres-exporter minio elasticsearch-master elasticsearch-master-headless -n dev

NAME                                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
rabbitmq-headless                                ClusterIP   None             <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   15h
rabbitmq                                         ClusterIP   172.20.171.21    <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   15h
postgres-postgresql-headless                     ClusterIP   None             <none>        5432/TCP                                4d22h
postgres-postgresql                              ClusterIP   172.20.177.95    <none>        5432/TCP                                4d22h
postgres-exporter-prometheus-postgres-exporter   ClusterIP   172.20.96.25     <none>        80/TCP                                  552d
minio                                            ClusterIP   172.20.157.199   <none>        9000/TCP                                4d20h
elasticsearch-master                             ClusterIP   172.20.42.230    <none>        9200/TCP,9300/TCP                       5d17h
elasticsearch-master-headless                    ClusterIP   None             <none>        9200/TCP,9300/TCP                       5d17h

rabbitmq section:

rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    address: rabbitmq.dev.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq
    password: ****** #here is my password of rabbitmq

**Comment by HardNorth** [comment]
@arnikasky Stack trace points on the specific line:
```none
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Unclassified Report Portal Error
	at com.epam.ta.reportportal.core.configs.rabbit.AnalyzerRabbitMqConfiguration.managementTemplate(AnalyzerRabbitMqConfiguration.java:56)
```

Could you please try putting `rabbitmq` into `SecretName` field and then redeploy the Report Portal instance? Let's see what it says on that.

**Comment by arnikasky** [comment]
Hello @HardNorth.
Set:
rabbitmq:
  SecretName: "rabbitmq"
  installdep:
    enable: false
  endpoint:
    address: rabbitmq.dev.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq
    password: *****
    
    
 it doesn't help.
The same errors and api pod doesn't start.
Checked, that there is the same passwords in secret rabbitmq and in values.yaml rabbitmq section.
I assume, it's not problem with rabbitmq, as when I deployed once with wrong password, I saw another error - 401 in logs of api pod.

**Comment by arnikasky** [comment]
Hello @HardNorth! Thank you for support. I found problem, I re-installed rabbitmq chart and faced with https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases  - Persistence Volumes (PVs) Retained From Previous Releases.  Now it works correctly.
