### ISSUE TITLE
how to use kubeseal in kubernetes approach

### ISSUE THREAD

**Issue by Mahesh81** [reportportal/kubernetes#207]
Hi
I am able to host the application using helm provided by community, i have question on secret management 

Organization uses vault, kubeseal and other approach for secret management . When we deploy using helm , how do we integrate and adhere to secret management options 
ex: helm install rmq --set auth.username=xxx, auth.password=xxx ../rabbitmq.tgz
I want to use kubeseal and extract the sealed password and run this cmd. please provide if there is other way of doing it

**Comment by hlebkanonik** [comment]
The right way is to ask the community responsible for Kubernetes secret management. ReportPortal uses Kubernetes to orchestrate containers, and our application can interact with any Kubernetes-compatible secrets managers.
