### ISSUE TITLE
Report portal - Elastic search Connection refused error

### ISSUE THREAD

**Issue by Mahesh81** [reportportal/kubernetes#212]
Hi Team
@HardNorth 
I installed report portal application in AWS EKS by manual command exection as per the instruction in https://github.com/reportportal/kubernetes/tree/master/reportportal
I tried to automate the same using spinnaker and i see issue with elastic search during the install with following error 
NAME                                  READY   STATUS    RESTARTS   AGE
pod/elastic-release-iwmqo-test-v000   0/1     Error     0          25m
pod/elasticsearch-master-0            0/1     Running   0          45s
pod/elasticsearch-master-1            0/1     Running   0          44s
pod/elasticsearch-master-2            0/1     Running   0          44s

NAME                                    TYPE           CLUSTER-IP       EXTERNAL-IP                                                                       PORT(S)                                        AGE
service/elasticsearch-master            LoadBalancer   10.100.218.131   internal-XXXXXus-west-2.elb.amazonaws.com   9200:31016/TCP,2222:31072/TCP,9300:32691/TCP   46s
service/elasticsearch-master-headless   ClusterIP      None             <none>                                                                            9200/TCP,9300/TCP,2222/TCP                     46s
service/kubernetes                      ClusterIP      10.100.0.1       <none>                                                                            443/TCP                                        10d

NAME                                    READY   AGE
statefulset.apps/elasticsearch-master   0/3     48s
mahesh@Mac_Admin’s charts % kubectl logs pod/elastic-release-iwmqo-test-v000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to elasticsearch-master port 9200: Connection refused

I am using version 7.6.1 as per requirements.yaml. i also tried upto 7.13.0 
I am not very familiar with helm and did my best to debug by changing to LoadBalancer; increased the timeout ; changed green to yellow for healthcheck - with no luck 

Can someone give me insight why it was failing through spinakker

**Comment by HardNorth** [comment]
@Mahesh81 I believe you are bypassing wrong elasticsearch host name, should be `elasticsearch-master.[namespace].svc.cluster.local` as here:
https://github.com/reportportal/kubernetes/blob/master/reportportal/values.yaml#L356
