### ISSUE TITLE
Needed support for Azure postgresql with SSL enabled

### ISSUE THREAD

**Issue by ghost** [reportportal/kubernetes#216]
Hello @DzmitryHumianiuk @HardNorth 

Does the report portal support Azure PostgreSQL with SSL enabled?
If Yes, how can we keep SSL enabled and deploy Azure PostgreSQL?

Thanks,
Deepalee Khare

**Comment by DzmitryHumianiuk** [comment]
@deepaleekhare31 it should be YES.
I don't see any reason no to work with Azure PG.

>If Yes, how can we keep SSL enabled and deploy Azure PostgreSQL? 
could you please elaborate here?

**Comment by hemant-karwade** [comment]
@DzmitryHumianiuk we are finding **SSL connection is required error** issue as when SSL enabled in AzurePG, 
![image](https://user-images.githubusercontent.com/53491176/140691541-b8013ee0-b72b-4b78-b2d0-dc5c1c092861.png)

**Comment by deepaleekhare31** [comment]
@DzmitryHumianiuk Even in documentation u have mentioned it as SSL should be enabled for Azure PostgreSQL. And keeping SSL enabled will give us the error as mentioned above by @hemant-karwade 
But not sure as to why is this a requirement ? And if we can keep it enabled ? Then how can we keep SSL enabled and deploy Azure PostgreSQL?

![IMG_20211108_160201](https://user-images.githubusercontent.com/50138350/140726682-c44c9335-d3a1-4fc7-aa31-6caf5e11a9cd.jpg)

**Comment by DzmitryHumianiuk** [comment]
@pbortnik any reason of disabled SSL above?

**Comment by deepaleekhare31** [comment]
Hello @pbortnik, Any updates on this?

**Comment by deepaleekhare31** [comment]
Hello @pbortnik, Any updates on this?

**Comment by Cyberglamdring** [comment]
Hello,

At now we don't support the SSL-enabled option for the database. However, you can manually prepare the database for the required migration version

**Option 1**
1. Install [golang migration](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate)
2. Clone [migration](https://github.com/reportportal/migrations) repo and `curl -LO https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x wait-for-it.sh` to ./migrations/ folder.
3. Use [offical guide](https://github.com/golang-migrate/migrate/tree/master/database/postgres) fo usage golang migration. For expample:
```BASH
./migrations/wait-for-it.sh <POSTGRES_SERVER>:<POSTGRES_PORT> -- migrate -path migrations/migrations -database postgres://<POSTGRES_USER>:<POSTGRES_PASSWORD>@<POSTGRES_SERVER>/<POSTGRES_DB>?sslcert=db.cret up
```
4. Check database migration version (for 5.6.0-5.6.2 RP version it will be `50`):
```SQL
select * from public.schema_migrations;
```
5. Install RP, as usual, using Helm and delete the migration job right away: `kubectl delete job.batch reportportal-migration`


**Option 2**
1. Clone [migration](https://github.com/reportportal/migrations)
2. Deploy every `up` script form ./migrations/migrations/ using `psql`
4. Check database migration version (for 5.6.0-5.6.2 RP version it will be `50`):
```SQL
select * from public.schema_migrations;
```
5. Install RP, as usual, using Helm and delete the migration job right away: `kubectl delete job.batch reportportal-migration`

**Comment by smartykhare** [comment]
Hello @Cyberglamdring, @DzmitryHumianiuk, @pbortnik  - Any updates on this?

**Comment by smartykhare** [comment]
Hello @Cyberglamdring, @DzmitryHumianiuk, @pbortnik - Any updates on this?

**Comment by smartykhare** [comment]
Hello  @Cyberglamdring, @DzmitryHumianiuk, @pbortnik, 

I recently deployed report portal (5.7.0) in my dev cluster.
Within the dev cluster deployment, one of the pods - "ReportPortal_Jobs" is trying to access the database (Azure PostgreSQL) and keeps restarting every 5 mins - giving the error (attached logs).

I understand its mandatory to keep SSL disabled for the deployement. And i have disabled the postgresql SSL, But still somewhere its trying to access SSL, and giving the below error.

Here is the command i ran:
_helm upgrade reportportal -n report-portal-dev --set rabbitmq.endpoint.address=rprabbitmq.report-portal-dev.svc.cluster.local,rabbitmq.endpoint.port=5672,rabbitmq.SecretName=rprabbitmq,postgresql.endpoint.address=p21d24308521001.postgres.database.azure.com,postgresql.endpoint.port=5432,postgresql.endpoint.user=pgadmin@p21d24308521001,postgresql.endpoint.dbName=reportportal,postgresql.endpoint.password=xxx-xxx-xxx,**postgresql.endpoint.ssl=disable**,minio.endpoint=http://rpminio.report-portal-dev.svc.cluster.local:9000,minio.endpointshort=rpminio.report-portal-dev.svc.cluster.local:9000,minio.accesskey=minio-accesskey,minio.secretkey=minio-secretkey,minio.secretName=rpminio,ingress.usedomainname=true,ingress.hosts[0]=reportportal.ffdcdev.fusionfabric.io,ingress.annotations.kubernetes\.io/ingress\.class=ffdcdev-private,serviceapi.replicaCount=5 ./reportportal-5.7.0.tgz_


Could you please help me with the reason/solution for the instability of the pod?


Error:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'calculateAllocatedStorageJob' defined in URL [jar:file:/service-jobs-5.6.3-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/jobs/storage/CalculateAllocatedStorageJob.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTemplate' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/JdbcTemplateConfiguration.class]: Unsatisfied dependency expressed through method 'jdbcTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/epam/reportportal/config/DataSourceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: SSL error: Connection reset by peer (Write failed)

[reportportal-jobs-579697c566-7t2hx.log](https://github.com/reportportal/kubernetes/files/8767795/reportportal-jobs-579697c566-7t2hx.log)

**Comment by sudeshjethoe** [comment]
I had the same issue, I installed the PostgreSQL bouncer inside the cluster as a proxy and ssl offloader

**Comment by HardNorth** [comment]
@sudeshjethoe so you don't use sdl, but have this issue, right?

**Comment by sudeshjethoe** [comment]
I just connect to a local pgbouncer deployment (without ssl) instead of the actual Azure Postgres database.

Pgbouncer then connects with the actual Azure database (with ssl)

**Comment by DzmitryHumianiuk** [comment]
thank you @sudeshjethoe 

https://www.pgbouncer.org/ link for reference.

**Comment by vitaliirymar** [comment]
> 

Hi @smartykhare! Could you please advise how have you managed to resolve the issue with the Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition? I'm facind the same during installation of RP 5.7.2 with Azure PostgreSQL Database.

**Comment by truyenhv** [comment]
> Hello @Cyberglamdring, @DzmitryHumianiuk, @pbortnik,
> 
> I recently deployed report portal (5.7.0) in my dev cluster. Within the dev cluster deployment, one of the pods - "ReportPortal_Jobs" is trying to access the database (Azure PostgreSQL) and keeps restarting every 5 mins - giving the error (attached logs).
> 
> I understand its mandatory to keep SSL disabled for the deployement. And i have disabled the postgresql SSL, But still somewhere its trying to access SSL, and giving the below error.
> 
> Here is the command i ran: _helm upgrade reportportal -n report-portal-dev --set rabbitmq.endpoint.address=rprabbitmq.report-portal-dev.svc.cluster.local,rabbitmq.endpoint.port=5672,rabbitmq.SecretName=rprabbitmq,postgresql.endpoint.address=p21d24308521001.postgres.database.azure.com,postgresql.endpoint.port=5432,postgresql.endpoint.user=pgadmin@p21d24308521001,postgresql.endpoint.dbName=reportportal,postgresql.endpoint.password=xxx-xxx-xxx,**postgresql.endpoint.ssl=disable**,minio.endpoint=[http://rpminio.report-portal-dev.svc.cluster.local:9000,minio.endpointshort=rpminio.report-portal-dev.svc.cluster.local:9000,minio.accesskey=minio-accesskey,minio.secretkey=minio-secretkey,minio.secretName=rpminio,ingress.usedomainname=true,ingress.hosts[0]=reportportal.ffdcdev.fusionfabric.io,ingress.annotations.kubernetes\.io/ingress\.class=ffdcdev-private,serviceapi.replicaCount=5](http://rpminio.report-portal-dev.svc.cluster.local:9000,minio.endpointshort=rpminio.report-portal-dev.svc.cluster.local:9000,minio.accesskey=minio-accesskey,minio.secretkey=minio-secretkey,minio.secretName=rpminio,ingress.usedomainname=true,ingress.hosts%5B0%5D=reportportal.ffdcdev.fusionfabric.io,ingress.annotations.kubernetes%5C.io/ingress%5C.class=ffdcdev-private,serviceapi.replicaCount=5) ./reportportal-5.7.0.tgz_
> 
> **Could you please help me with the reason/solution for the instability of the pod?**
> 
> Error:
> 
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'calculateAllocatedStorageJob' defined in URL [jar:file:/service-jobs-5.6.3-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/jobs/storage/CalculateAllocatedStorageJob.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTemplate' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/JdbcTemplateConfiguration.class]: Unsatisfied dependency expressed through method 'jdbcTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/epam/reportportal/config/DataSourceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: SSL error: Connection reset by peer (Write failed)
> 
> [reportportal-jobs-579697c566-7t2hx.log](https://github.com/reportportal/kubernetes/files/8767795/reportportal-jobs-579697c566-7t2hx.log)

Hi @smartykhare Did you manage this issue? I'm facing with that now.
