### ISSUE TITLE
typo in step 10 Report portal command in readme

### ISSUE THREAD

**Issue by shivamkasat** [reportportal/kubernetes#237]
command given: `helm install <reportportal-release-name> --set postgresql.SecretName=<postgresql-release-name>-postgresql,rabbitmq.SecretName=<rabbitmq-release-name>-rabbitmq,minio.secretName=<minio-release-name> ./reportportal-5.6.0.tgz`
if you'll notice minio.secretName has "s" but it should be "S", oberserving SecretName key in values.yaml file.
command should be: `helm install <reportportal-release-name> --set postgresql.SecretName=<postgresql-release-name>-postgresql,rabbitmq.SecretName=<rabbitmq-release-name>-rabbitmq,minio.SecretName=<minio-release-name> ./reportportal-5.6.0.tgz`

**Comment by HardNorth** [comment]
That's not correct:
https://github.com/reportportal/kubernetes/blob/develop/reportportal/values.yaml#L210

**Comment by shivamkasat** [comment]
my bad! Might have been some mistake from my end. Sorry to bother
