### ISSUE TITLE
Dirty database version 0. Fix and force version.

### ISSUE THREAD

**Issue by JonhDon** [reportportal/kubernetes#246]
Hi, have an error related to the migration job. Migration job is to fail with error "error: Dirty database version 0. Fix and force version." when connecting reporportal DB.
Screenshot: 
![image](https://user-images.githubusercontent.com/83138978/161569695-3a238b06-4473-4390-97ba-3fb9ec2abb36.png)

Could you help me resolve the current error?

And I wish that to push your changes from develop to master branch because on develop branch you have resolved many bugs, that remained in the master branch.

**Comment by ysenturk1** [comment]
Hey @JonhDon can you tell me what did you do to fix this by any chance? We are facing the same issue.
