### ISSUE TITLE
Ability to override service names in service definition to match Istio naming conventions.

### ISSUE THREAD

**Issue by damongabrielle** [reportportal/kubernetes#253]
We deploy Report Portal behind Istio Gateway and we terminate TLS at the gateway. We leave the Report Portal Services as HTTP. Currently the Envoy sidecar improperly guesses the right protocol to use between Envoy and Report Portal Services. There are [several variations of this issue](https://istio.io/latest/docs/ops/common-problems/network-issues/#tls-configuration-mistakes) described on Istio's common problems page. 

The reason Istio guesses incorrectly, at least in my case, is because the Report Portal service names are all named "headless". 

You can force Istio to use the right protocol by matching certain conventions in your service definition.

Here is [the section of the Istio doc](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection) that describes explicit protocol selection. Your service names must either match the convention `<protocol>[-<suffix>] ` OR fill in the `appVersion` field in order to get Istio to handle forwarding the traffic properly. If you don't then you get a 400 error response. 

It doesn't appear that either of these solutions are feasible in Report Portals' service templates. 

As a workaround I've gone ahead and created my own services that are identical to the current services, except they have the name: http-headless, to match Istio's conventions. This fixed Istio's protocol selection. 

To avoid creating duplicate services, I'd like to propose that Report Portal either allows overriding ALL services names in the Values.yaml (I prefer this since this is what I tested) or expose the appVersion field in the values.yaml. I'm not sure the appVersion option is the best since that requires Kubernetes 1.18+, I'd have to check if that meets report portals minimum k8 version, and I haven't tested this option.

Assuming you were ok with overriding the services names, take the index service as an example:
```
spec:
  ports:
  - name: headless
```
It's be great if it was this instead:

```
spec:
  ports:
  - name: {{ $.Values.serviceindex.protocol | default "headless" }}
```
and then do this for each service.

I'm happy to create a PR for this if you'd find that helpful.

**Comment by HardNorth** [comment]
I would not name value parameter as "protocol", since might be confused with service protocol itself. People may put here "https" expecting "serviceindex" will start serve HTTPS requests. I would named it something like "portName". Apart from that go ahead, create a PR.

**Comment by damongabrielle** [comment]
Hi @HardNorth, 
Thanks! Good catch! Totally agree. Ok, I will open a PR in the next day or so with something like this for each service:

`{{ $.Values.serviceindex.portName | default "headless" }}`

Side note: This service doesn't appear to actually be headless given it has a type of ClusterIP. It threw me off at first when debugging my Istio issue until I took note of what the type field was set to. I thought maybe my issue was related to proxying headless services which has its own considerations in Istio. I'm not asking to change this but thought it was worth pointing out while we're discussing a change to the same line of code. Maybe the implications of changing the default value is more significant than it appears or maybe it used to be headless and the name is an artifact of that. I'll plan to keep it the same in my PR unless you have different thoughts.

**Comment by DzmitryHumianiuk** [comment]
@damongabrielle can we close it now?

**Comment by damongabrielle** [comment]
Yes, sounds good to me @DzmitryHumianiuk
