### ISSUE TITLE
Kubernetes Jobs pod is getting restarted several times due to SSL error 

### ISSUE THREAD

**Issue by smartykhare** [reportportal/kubernetes#258]
Hello @Cyberglamdring, @DzmitryHumianiuk, @pbortnik

I recently deployed report portal (5.7.0) in my dev cluster using Azure Database for PostgreSQL.
Within the dev cluster deployment, one of the pods - "ReportPortal_Jobs" is trying to access the database (Azure PostgreSQL) and keeps restarting every 5 mins - giving the error (attached logs). you can see the attached screenshot where the pod restarted 155 times within 20hours.

I understand it's mandatory to keep SSL disabled for the deployment. And I have disabled the PostgreSQL SSL, But still, somewhere within the Jobs pod it's trying to access SSL, and giving the below error.

Here is the command I ran:
helm upgrade reportportal -n report-portal-dev --set rabbitmq.endpoint.address=rprabbitmq.report-portal-dev.svc.cluster.local,rabbitmq.endpoint.port=5672,rabbitmq.SecretName=rprabbitmq,postgresql.endpoint.address=p21d24308521001.postgres.database.azure.com,postgresql.endpoint.port=5432,postgresql.endpoint.user=pgadmin@p21d24308521001,postgresql.endpoint.dbName=reportportal,postgresql.endpoint.password=xxx-xxx-xxx,postgresql.endpoint.ssl=disable,minio.endpoint=[http://rpminio.report-portal-dev.svc.cluster.local:9000,minio.endpointshort=rpminio.report-portal-dev.svc.cluster.local:9000,minio.accesskey=minio-accesskey,minio.secretkey=minio-secretkey,minio.secretName=rpminio,ingress.usedomainname=true,ingress.hosts[0]=reportportal.ffdcdev.fusionfabric.io,ingress.annotations.kubernetes\.io/ingress\.class=ffdcdev-private,serviceapi.replicaCount=5](http://rpminio.report-portal-dev.svc.cluster.local:9000%2Cminio.endpointshort%3Drpminio.report-portal-dev.svc.cluster.local:9000,minio.accesskey=minio-accesskey,minio.secretkey=minio-secretkey,minio.secretName=rpminio,ingress.usedomainname=true,ingress.hosts%5B0%5D=reportportal.ffdcdev.fusionfabric.io,ingress.annotations.kubernetes%5C.io/ingress%5C.class=ffdcdev-private,serviceapi.replicaCount=5) ./reportportal-5.7.0.tgz

Could you please help me with the reason/solution for the instability of the pod?

Error:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'calculateAllocatedStorageJob' defined in URL [jar:file:/service-jobs-5.6.3-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/jobs/storage/CalculateAllocatedStorageJob.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTemplate' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/JdbcTemplateConfiguration.class]: Unsatisfied dependency expressed through method 'jdbcTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/epam/reportportal/config/DataSourceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: SSL error: Connection reset by peer (Write failed)
logs:
[reportportal-jobs-579697c566-7t2hx.log](https://github.com/reportportal/kubernetes/files/8767795/reportportal-jobs-579697c566-7t2hx.log)

![image](https://user-images.githubusercontent.com/96837986/170178055-285c8be2-bafb-4721-a656-491460e70a9c.png)

**Comment by smartykhare** [comment]
Hello @Cyberglamdring, @DzmitryHumianiuk, @pbortnik
Any updates on this ?

**Comment by HardNorth** [comment]
@smartykhare we had an issue in `values.yaml` file, `postgresql . ssl ` was specified incorrectly: `disabled` instead of `disable`. Please update the value manually.
