### ISSUE TITLE
Migrate Helm to API version 2

### ISSUE THREAD

**Issue by avarabyeu** [reportportal/kubernetes#262]
Current Chart is built on API Version 1 which becomes obsolete. 
helm version 3.9.0
error:
`Error: can't get a valid version for repositories postgresql, rabbitmq, minio. Try changing the version constraint in Chart.yaml`

**Comment by HardNorth** [comment]
@avarabyeu I just installed everything with helm `3.10.1` without any issues. Could you describe your actions to get such error?

**Comment by HardNorth** [comment]
@avarabyeu Well, actually I update `Chart.yaml` on version 2, so you can try to install from this branch: https://github.com/reportportal/kubernetes/tree/chart-v2

**Comment by HardNorth** [comment]
Well, we already have requirement on Helm V3, so no point to stick to Chart v1. So fixed.
