### ISSUE TITLE
Update values.yaml and documentation for TLS

### ISSUE THREAD

**Issue by bkonicek** [reportportal/kubernetes#263]
The documentation for setting up SSL/TLS instructs to add the `tls` block to  `gateway-ingress.yaml`. However since this is a Helm chart, it would be much easier if you added `tls` inside the `ingress` section of `values.yaml`. The helm template already supports this but it doesn't do anything without modifying `values.yaml` currently.

For example
```
ingress:
  tls:
  enable: true
  ...
```

**Comment by Gl-Canon** [comment]
Hello @bkonicek, thanks for advise. I will add `tls: true` in the feature realise.
