### ISSUE TITLE
Deprecation of the MinIO gateway

### ISSUE THREAD

**Issue by alenhodzic85** [reportportal/kubernetes#269]
Hi,
Minio is depricating MinIO gateway https://blog.min.io/deprecation-of-the-minio-gateway/. Any plans to support S3 directly?

Ref. https://github.com/reportportal/kubernetes/issues/114

Thanks,

**Comment by throwawayaccount11111** [comment]
Why is this closed without any comment from reportportal folks? Is this issue fixed now or rolled out?

**Comment by HardNorth** [comment]
We are in the process of migration to `jclouds` library:
https://github.com/reportportal/commons-dao/pull/849
