### ISSUE TITLE
New deployment - k8s migrations job halts at "59/u stale_materialized_view"

### ISSUE THREAD

**Issue by joeykb** [reportportal/kubernetes#276]
I have deployed reportportal on Kubernetes (GKE).  During the deployment, the migrations job runs and stops at 
`59/u stale_materialized_view`

Postgres DB reportportal shows table and index created according to https://github.com/reportportal/migrations/blob/develop/migrations/59_stale_materialized_view.up.sql

Anyone run into something similar?

**Comment by miracle8484** [comment]
Hello, @joeykb, we need more details to be able to help you. At least could you show logs of migration, please?

**Comment by joeykb** [comment]
I was able to get past this by removing our istio sidecar.  In order to do this, I had to modify the helm chart to allow pod labels.
But, when I look at the tables in the database, the SQL commands for 60-64 do not seem to have run because the tables in those commands did not exist.

**Comment by miracle8484** [comment]
Hello, @joeykb, could you try to execute manually https://github.com/reportportal/migrations/blob/develop/migrations/59_stale_materialized_view.up.sql 
on database and share result.
if stale_materialized_view is already created, than please drop it from the beginning. (https://github.com/reportportal/migrations/blob/develop/migrations/59_stale_materialized_view.down.sql).
Also could you provide postgresql version, and may be you have some custom time restriction for query execution for example?
Thx

**Comment by hlebkanonik** [comment]
There was no response from the requestor.
