### ISSUE TITLE
Minio S3 gateway deprecation

### ISSUE THREAD

**Issue by throwawayaccount11111** [reportportal/kubernetes#282]
I have seen some issues and conversation around this topic but all issues are closed without any guidance or next steps from report portal folks.

If s3 gateway is being deprecated, when does reportPortal will be updated to make use of S3 API?

**Comment by HardNorth** [comment]
@throwawayaccount11111 Please don't spam with issues.
As for Minio we are in the process of migration to `jclouds` library:
https://github.com/reportportal/commons-dao/pull/849
