### ISSUE TITLE
serviceui securityContext issue

### ISSUE THREAD

**Issue by zptepam** [reportportal/kubernetes#287]
I have a Kubernetes based deployment in a shared environment with the following version numbers:

- API Service: 5.7.1;
- Jobs Service: 5.7.1;
- Authorization Service: 5.7.0;
- Service UI: 5.6.0;   <-- this is left 5.6.0 at the previous upgrade due to the below error

I would like to upgrade to release 5.7.3. 
Templates and values files have been updated accordingly but I face the following error with **serviceui**:

_CreateContainerConfigError (container has runAsNonRoot and image will run as root (pod: "reportportal-ui-xxx(...)", container: ui))_

This is related to the configuration of **securityContext** as the deployment is in a shared environment that has some limitations regarding how containers could be executed.

The default setting is: 

**securityContext: {}** 

For other RP containers the following workaround is a good solution. securityContext is adjusted a bit:

**securityContext:
runAsUser: 1000**

This works for all other RP containers but not for serviceui from 5.7.0 and above.

I face the following error if securityContext is adjusted as mentioned above:

_/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d//docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh/docker-entrypoint.sh: Configuration complete; ready for start up
2023/01/19 10:21:00 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)_

I assume user settings should be fixed in the container image to support the workaround as it works for all other RP containers that need this (serviceindex, uat, serviceapi, servicejobs, migrations, serviceanalyzer, serviceanalyzertrain, metricsgatherer) except for serviceui.

Could you please advise?

Thanks,

**Comment by avarabyeu** [comment]
RP team, this could be solved by switching over to rootless NGINX base image: 
https://stackoverflow.com/questions/63108119/how-to-run-an-nginx-container-as-non-root

**Comment by AmsterGet** [comment]
Hello @zptepam @sjyzheng !
We've published [5.7.3-non-root](https://hub.docker.com/layers/reportportal/service-ui/5.7.3-nonroot/images/sha256-94e647f9a9e0378b864542d04f7758649b633e8db7df8494c46efc1d1b0928b1?context=explore) and [5.7.4-non-root](https://hub.docker.com/layers/reportportal/service-ui/5.7.4-nonroot/images/sha256-97cee04981d308db95f67834f80775cd96d0c7696d620c138191da8f82edc8ca?context=explore) images as @avarabyeu suggested that fixes your issues.
Please note, that from ReportPortal version 23.1 the UI service (from service version [5.8.0](https://hub.docker.com/layers/reportportal/service-ui/5.8.0/images/sha256-37e484ec7868915833c54016e9031c500ac3e686a67777b958e3ae8659b9b2f2?context=explore)) will be built on top of the rootless NGINX image by default.
