### ISSUE TITLE
Report portal page stuck on loading after installation on Ubuntu 22.04, k3s v1.24+k3s

### ISSUE THREAD

**Issue by assiakhateeb** [reportportal/kubernetes#288]
I have installed report portal according to the instructions provided in this documentation: [Install ReportPortal](https://epam.github.io/edp-install/operator-guide/install-reportportal/) on k3s v1.24+k3s1 running on an Ubuntu 22.04 (64-bit) VM.

Access to the "report-portal-reportportal-ui" service has been established using kubectl port forwarding on port 8080, however, the page is stuck on loading. No errors have been detected in the pods logs and all pods are running.

CPU and memory usage have been checked and no issues have been identified.

**Steps to Reproduce:**

- Installation of report portal using the above-mentioned documentation

- Connection to "report-portal-reportportal-ui" service using kubectl port forwarding on port 8080

**Expected Behavior:**

- The report portal page should load correctly

**Actual Behavior:**

- The report portal page is stuck on loading

**Environment:**

- Ubuntu 22.04 (64-bit)
- k3s v1.24.6+k3s1 (a8e0c66d)
- kubectl version 1.23.0 
- Helm version 3.10.2
- RP version 5.7.3

**Screenshots**
<img width="1346" alt="Screenshot 2023-01-22 at 19 25 25" src="https://user-images.githubusercontent.com/39053503/213930567-ed040758-3f25-4bf9-85e6-8f393bc05a17.png">

<img width="1340" alt="Screenshot 2023-01-22 at 19 25 57" src="https://user-images.githubusercontent.com/39053503/213930560-bb402a00-30f2-44cd-b8a9-edfd7286d29f.png">

**Comment by ysenturk1** [comment]
We are on a similar boat, hoping you can get an update on this soon!

**Comment by safredAAs** [comment]
Same issue, any resolution/help?
