### ISSUE TITLE
Dynamic provisionin - improve helm chart

### ISSUE THREAD

**Issue by dusansusic** [reportportal/kubernetes#3]
On non-minikube environments, but cloud ones such as aws, gcp, azure, we have dynamic provisioning.
As you provided PersistentVolume and PersistentVolumeClaim, then you should make conditionals to helm chart to not use PersistentVolumes when dynamic provisioning is in use. Therefore, only PVC is need.
vaules.yaml must be updated accoring to that - remove hostPath sections.
More at [this link.](https://kubernetes.io/blog/2016/10/dynamic-provisioning-and-storage-in-kubernetes/)

**Comment by avarabyeu** [comment]
Fixed for v5
