### ISSUE TITLE
Support for Kubernetes 1.25+

### ISSUE THREAD

**Issue by vitaliydavydiak** [reportportal/kubernetes#311]
Currently there is a requirement: Kubernetes v1.19-1.24

v1.24.x support will be discontinued on Microsoft Azure soon.

The main blocker seems to be Elastic 8.x compatibility. 
Elastic 7.x charts are not compatible with 1.25+ due to breaking changes while ReportPortal seems to be unstable with Elastic 8.x.

Are there any plans to support newer versions of Kubernetes?

**Comment by Idosegal** [comment]
We are using EKS and 1.24 is going to be deprecated at the end of Jan 2024.
Are there any plans to support newer versions of Kubernetes?

**Comment by Idosegal** [comment]
When the new version support 1.25+ will be released? We can see changes in develop but not released yet.
