### ISSUE TITLE
upgrade 5.7.4 - 5.8.0 uat password

### ISSUE THREAD

**Issue by Mieszko96** [reportportal/kubernetes#312]
When i wanted to upgrade reportportal i am getting error

```
Error: template: reportportal/templates/uat-secret.yaml:31:24: executing "reportportal/templates/uat-secret.yaml" at <index (lookup "v1" "Secret" .Release.Namespace "{{ template reportportal.name . }}-superadmin-passwd").data "superadmin-passwd">: error calling index: index of untyped nil
```
 
 i checked this template https://github.com/reportportal/kubernetes/blob/develop/reportportal/templates/uat-secret.yaml
 
 and i see reportportal creating this secret only on brand new installation

 ```
 data:
  {{- if .Release.IsInstall }}
  superadmin-passwd: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  superadmin-passwd: {{ index (lookup "v1" "Secret" .Release.Namespace "{{ template reportportal.name . }}-superadmin-passwd").data "superadmin-passwd" }}
  {{ end }}
  ```
  
  
  I don't have this secret in my 5.7.4(i was previously updating from 5.6.0)
  
  I managed to fix it by providing(at least --dry-run runs fine)
  ```
  "uat" = {
      "superadminInitPasswd" = {
        "auto"     = false
        "password" = "somepassword"
      }
    }
   ```

Is it a bug?

**Comment by AsoTora** [comment]
Same here, after initial installation:

```
helm upgrade --install reportportal -f values.yml -n reportportal ./reportportal-5.8.0.tgz
Error: UPGRADE FAILED: template: reportportal/templates/uat-secret.yaml:31:24: executing "reportportal/templates/uat-secret.yaml" at <index (lookup "v1" "Secret" .Release.Namespace "{{ template reportportal.name . }}-superadmin-passwd").data "superadmin-passwd">: error calling index: index of untyped nil
```

**Comment by sharkymcdongles** [comment]
Ya this is broken because even if the secret is created the way it looks up the value is wrong.

**Comment by assiakhateeb** [comment]
any updates?

**Comment by hlebkanonik** [comment]
Hi! Starting from chart version 5.8.1, the autogenerated secret has been removed. Please update the chart or merge changes [here](https://github.com/reportportal/kubernetes/blob/reportportal-5.10.0/reportportal/values.yaml#L61) and [here](https://github.com/reportportal/kubernetes/blob/reportportal-5.10.0/reportportal/templates/uat-deployment.yaml#L47C9-L62C19)

Also take a look at the [develop](https://github.com/reportportal/kubernetes) branch. We are working on a major changes of the helm chart for the upcoming release.
