### ISSUE TITLE
Latest version of PostgreSQL and Minio charts

### ISSUE THREAD

**Issue by sergiobortsov** [reportportal/kubernetes#339]
Hello!
We've tried to upgrade the dependency charts for postgres (to 12.12.10) and minio (to the latest) and it worked with some small changes for the secrets keys names. But Reportportal API didn't work properly due to missing columns in the database:

column sendercase2_.attributes_operator does not exist

I believe it happened because of the failed migrations caused by different postgres server version.
Are there any plans to update the migrations or/and Helm chart for Reportportal with a proper support of the Postgres version 15 (at least)?

Thanks

**Comment by hlebkanonik** [comment]
Hi! We have updated MinIO, PostgreSQL, and RabbitMQ to the latest version in ReportPortal 24.2 release. Moreover, we will update all dependencies in each feature release.
