### ISSUE TITLE
Issue: Installing reportportal deployment is failing

### ISSUE THREAD

**Issue by decipher27** [reportportal/kubernetes#353]
Hi Folks,

Our EKS is on 1.28 k8s version and we are testing out deploying reportportal deployment. 
We have configured the Chart.yaml as below and pulling all changes from upstream. 

```Ruby
apiVersion: v2
name: reportportal
description: ReportPortal.io AI-powered Test Automation Dashboard
type: application
version: 1.0.0
appVersion: "23.2"
dependencies:
  - name: reportportal
    version: 5.10.0
    repository: https://reportportal.io/kubernetes/
```
Custom changes  done on values.yaml
```Ruby
reportportal:

  serviceapi:
    ## Configure Audit logs to be written to the API container's directory /var/log/reportportal/audit.log
    auditLogs:
      ## Enable or disable the sidecar log streamer container
      enable: true #disabled by default
```
We use ArgoCD as CD tool for kubernetes and have the app successfully created pointing to the confugration. 

At first, we noticed a migration job is being run that interacts with postgresql and elasticsearch but failing to find the endpoint.

Find the below error for the migration job:
```Ruby
nc: bad address '<postgresql-release-name>-postgresql.default.svc.cluster.local'
nc: bad address '<postgresql-release-name>-postgresql.default.svc.cluster.local'
nc: bad address '<postgresql-release-name>-postgresql.default.svc.cluster.local'
```

Questions?
1. Why a migration job is being run during initial deployment when this is a fresh install? 
2. If the migration job is trying to hit postgresql - doesn't it mean that postgres and other dependent services should ideally be installed first? 
3. If you can point us to the right documentation.

Let us know if you require any more information.

Thanks!

**Comment by hlebkanonik** [comment]
Hi! 

We have released the [new version of the Helm Chart](https://github.com/reportportal/kubernetes/releases/tag/reportportal-23.2.0). Please proceed to install it now.

## Q/A
> Why a migration job is being run during initial deployment when this is a fresh install?

[Migrations](https://github.com/reportportal/migrations/tree/5.11.0) prepare the database for ReportPortal 

> If the migration job is trying to hit postgresql - doesn't it mean that postgres and other dependent services should ideally be installed first?

In the new Helm Chart version 23.2.0, all dependent services are installed with the Helm Chart. Additionally, you have the option to use external cloud services such as Amazon RDS Postgres for the database, Amazon OpenSearch, and AmazonMQ as the RabbitMQ message broker. 

Useful links:
1. [Chart.yaml ](https://github.com/reportportal/kubernetes/blob/reportportal-23.2.0/reportportal/Chart.yaml#L13)
2. [External dependencies installation configuration](https://github.com/reportportal/kubernetes/blob/reportportal-23.2.0/reportportal/values.yaml#L603)

**Comment by decipher27** [comment]
Thanks @hlebkanonik ! 
We are installing the reportportal helm chart via ArgoCD [A dedicated app is created for it] and noticed that the resources are not getting deployed and are in OutOfSync state.
I did try installing manually via helm and was able to open up the UI. 
Any idea what might be wrong here? 

<img width="839" alt="image" src="https://github.com/reportportal/kubernetes/assets/30067293/6a03b227-b10b-4733-b5fa-b3d8ac2be815">

**Comment by decipher27** [comment]
Hi Folks, any suggestions here that can help?

**Comment by hlebkanonik** [comment]
@decipher27, Could you share the logs or service events?
