### ISSUE TITLE
Reportportal k8s new installation is stuck on new version 23.2 (and even 23.1)

### ISSUE THREAD

**Issue by ravinice** [reportportal/kubernetes#357]
I m working on a new install with helm for version 23.2 and the installation is stuck while bringing up the pods. Lot of pods are getting stuck at PodInitiatlizing phase but the migrations pod is running and it shows that 72 sql scripts are run (no logs after that)

**My setup:**
Note: Prerequisites for hardware requirements are met. It is a 3 node cluster with 1 master and 2 worker nodes with more than 8 CPU each and 8GB RAM each.

1. postgres db installed separately in a different namespace on the same cluster
2. Used below command to perform the helm install
```
helm install reportportal \
  --set postgresql.install=false \
  --set database.endpoint=postgres.postgres-ns.svc.cluster.local \
  --set database.port=5432 \
  --set database.user=rp_user \
  --set database.password=dbpass1\
  reportportal/reportportal --version 23.2 \
  --namespace reportportal23
```
  
3. Below is the status of the pods:

> [root@kube-master kubernetes]# k get nodes
> NAME         STATUS   ROLES           AGE   VERSION
> ent-000123   Ready    <none>          12h   v1.28.2
> ent-003456   Ready    control-plane   36h   v1.29.1
> ent-003789   Ready    <none>          35h   v1.29.1
> [root@ENT-003459 kubernetes]#

> [root@kube-master ~]# k get po -n reportportal23
> NAME                                             READY   STATUS     RESTARTS   AGE
> opensearch-cluster-master-0                      0/1     Pending    0          2m54s
> reportportal-analyzer-0                          0/1     Init:0/1   0          2m54s
> reportportal-analyzer-train-0                    0/1     Init:0/1   0          2m54s
> reportportal-api-5498f85876-ts82v                0/1     Init:0/1   0          2m54s
> reportportal-index-b7b9cc688-mzpp4               1/1     Running    0          2m54s
> reportportal-jobs-94bd7496f-b9xds                0/1     Init:0/1   0          2m54s
> reportportal-metrics-gatherer-6965475c86-44rp8   0/1     Init:0/1   0          2m54s
> reportportal-migrations-4zxp8                    1/1     Running    0          2m54s
> reportportal-minio-68669b7c9d-g46qx              0/1     Pending    0          2m54s
> reportportal-rabbitmq-0                          0/1     Pending    0          2m54s
> reportportal-uat-67ddf678bd-g44pn                0/1     Init:0/1   0          2m54s
> reportportal-ui-678f95d9f5-lgfzc                 1/1     Running    0          2m54s
> [root@kube-master ~]#
> 

> [root@kube-master ~]#k get deployments -n reportportal23
> NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
> reportportal-api                0/1     1            0           16m
> reportportal-index              1/1     1            1           16m
> reportportal-jobs               0/1     1            0           16m
> reportportal-metrics-gatherer   0/1     1            0           16m
> reportportal-minio              0/1     1            0           16m
> reportportal-uat                0/1     1            0           16m
> reportportal-ui                 1/1     1            1           16m
> [root@kube-master ~]#

5.  Below are the last 5 lines of all pods:

> [root@kube-master kubernetes]# k logs --tail=5 opensearch-cluster-master-0 -n reportportal23
> Defaulted container "opensearch" out of: opensearch, fsgroup-volume (init)
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-analyzer-0 -n reportportal23
> Defaulted container "analyzer" out of: analyzer, migrations-waiting-init (init)
> Error from server (BadRequest): container "analyzer" in pod "reportportal-analyzer-0" is waiting to start: PodInitializing
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-analyzer-train-0 -n reportportal23
> Defaulted container "analyzer-train" out of: analyzer-train, migrations-waiting-init (init)
> Error from server (BadRequest): container "analyzer-train" in pod "reportportal-analyzer-train-0" is waiting to start: PodInitializing
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-api-5498f85876-ts82v -n reportportal23
> Defaulted container "api" out of: api, migrations-waiting-init (init)
> Error from server (BadRequest): container "api" in pod "reportportal-api-5498f85876-ts82v" is waiting to start: PodInitializing
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-index-b7b9cc688-mzpp4 -n reportportal23
> 2024/02/07 18:40:47 "GET http://192.144.213.18:8080/health HTTP/1.1" from 10.10.77.29:55240 - 200 16B in 40.654µs
> 2024/02/07 18:40:57 "GET http://192.144.213.18:8080/health HTTP/1.1" from 10.10.77.29:55318 - 200 16B in 43.118µs
> 2024/02/07 18:41:07 "GET http://192.144.213.18:8080/health HTTP/1.1" from 10.10.77.29:55396 - 200 16B in 41.496µs
> 2024/02/07 18:41:17 "GET http://192.144.213.18:8080/health HTTP/1.1" from 10.10.77.29:55468 - 200 16B in 40.732µs
> 2024/02/07 18:41:27 "GET http://192.144.213.18:8080/health HTTP/1.1" from 10.10.77.29:55542 - 200 16B in 45.06µs
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-jobs-94bd7496f-b9xds -n reportportal23
> Defaulted container "jobs" out of: jobs, migrations-waiting-init (init)
> Error from server (BadRequest): container "jobs" in pod "reportportal-jobs-94bd7496f-b9xds" is waiting to start: PodInitializing
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-metrics-gatherer-6965475c86-44rp8 -n reportportal23
> Defaulted container "metrics-gatherer" out of: metrics-gatherer, migrations-waiting-init (init)
> Error from server (BadRequest): container "metrics-gatherer" in pod "reportportal-metrics-gatherer-6965475c86-44rp8" is waiting to start: PodInitializing
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-migrations-4zxp8 -n reportportal23
> 68/u api_key_last_used_at (161.178996ms)
> 69/u replace_activity_table (158.076163ms)
> 70/u trigger_on_user_delete (157.907329ms)
> 71/u user_bid_inviting_user_id (157.054236ms)
> 72/u add_attachment_name (147.300641ms)
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-minio-68669b7c9d-g46qx -n reportportal23
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-rabbitmq-0 -n reportportal23
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-uat-67ddf678bd-g44pn -n reportportal23
> Defaulted container "uat" out of: uat, migrations-waiting-init (init)
> Error from server (BadRequest): container "uat" in pod "reportportal-uat-67ddf678bd-g44pn" is waiting to start: PodInitializing
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-ui-678f95d9f5-lgfzc -n reportportal23
> 10.10.77.29 - - [07/Feb/2024:18:41:57 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.28"
> 10.10.77.29 - - [07/Feb/2024:18:42:07 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.28"
> 10.10.77.29 - - [07/Feb/2024:18:42:17 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.28"
> 10.10.77.29 - - [07/Feb/2024:18:42:27 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.28"
> 10.10.77.29 - - [07/Feb/2024:18:42:37 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.28"
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]#
> [root@kube-master kubernetes]# k logs --tail=5 reportportal-api-5498f85876-ts82v -c migrations-waiting-init -n reportportal23
> [2024-02-07 18:45:36] Waiting for job reportportal-migrations...
> [2024-02-07 18:45:40] Waiting for job reportportal-migrations...
> [2024-02-07 18:45:44] Waiting for job reportportal-migrations...
> [2024-02-07 18:45:47] Waiting for job reportportal-migrations...
> [2024-02-07 18:45:51] Waiting for job reportportal-migrations...
> [root@kube-master kubernetes]#

**Comment by Pink-Bumblebee** [comment]
@ravinice are you still having this issue?

**Comment by ravinice** [comment]
@Pink-Bumblebee 
I was able to make some progress and all except one of the pods have come up fine now (after creating local persistent volumes).

And, the UI still shows blank screen with "Loading" message.

I see below error on the reportportal-uat pod.

```
2024-02-09 07:25:44.084  INFO 1 --- [           main] c.e.r.auth.AuthServerApplication         : Started AuthServerApplication in 65.988 seconds (JVM running for 68.896)
2024-02-09 07:25:44.694 ERROR 1 --- [           main] c.e.r.auth.AdminPasswordInitializer      : Password not set in environment variable

```

How/where do I see this password for that pod?
Is this the RP_INITIAL_ADMIN_PASSWORD ?

**Comment by Pink-Bumblebee** [comment]
helm install my-release --set uat.superadminInitPasswd.password="**_MyPassword_**" reportportal/reportportal

**Comment by ravinice** [comment]
@Pink-Bumblebee 

Thanks - that worked.

All the pods are in Running status and I see no errors in the logs but the UI is not loading. I get a blank screen with just "Loading" message

In browser dev tools - I see below error:
main.app.ffa3d937.js:1 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at main.app.ffa3d937.js:1:216110

**Comment by ravinice** [comment]
Ignore my comment above - I was trying to use port-forward to access the report portal UI which didn't work.
So, I just installed metallb which worked and I can access the reportportal ui now.

**Comment by ravinice** [comment]
Closing the ticket as I am able to get the Report portal up running now.

Issues that I had to fix to resolve my issues:
1. Not having persistent volumes or default storage class in the my cluster (running on baremetal)
2. Not passing  uat.superadminInitPasswd.password as part of the helm install
3. DB user to be used for reportportal should be SUPERUSER

**Comment by ravinice** [comment]
Thanks for the help @Pink-Bumblebee
