### ISSUE TITLE
[HELP] every route prefixed with /reportportal

### ISSUE THREAD

**Issue by prasad89** [reportportal/kubernetes#360]
Hello everyone,

I'm setting up ReportPortal on my EKS environment.
My requirement is to have every route prefixed with /reportportal.
I added the environment variable `RESOURCE_PATH=/reportportal` in the index section only, and I'm able to access the login screen.
However, subsequent requests are going to /uat and /api instead of /reportportal/uat and /reportportal/api respectively.

How can I meet my specific requirements?
Thank you in advance.

**Comment by Pink-Bumblebee** [comment]
Hello @prasad89 , maybe information from this thread will be helpful: https://github.com/reportportal/kubernetes/issues/116

**Comment by Pink-Bumblebee** [comment]
@prasad89 , this option (to change route) will be implemented in Release v24.1

**Comment by prasad89** [comment]
Can you provide detailed solution for this?
