### ISSUE TITLE
migration job doesn't use secrets for ElasticSearch

### ISSUE THREAD

**Issue by yurabrovka** [reportportal/kubernetes#367]
The migration job doesn't use secret for ElasticSearch
`- name: OS_PASSWORD
    value: "{{ .Values.searchengine.password }}"`

**Comment by hlebkanonik** [comment]
Thank you for bringing this to our attention. We will work on resolving it in the develop branch and include it in the upcoming release, which should be available in a few weeks.

**Comment by hlebkanonik** [comment]
Changes has been added with commit  https://github.com/reportportal/kubernetes/commit/6f04982281eaa17f490cae498df72d95b4f5825d to the `develop` branch. In a few weeks, it will be released as version 24.1.
