### ISSUE TITLE
Extra toleration line in service-authorization/uat-deployment.yaml

### ISSUE THREAD

**Issue by ctsscott** [reportportal/kubernetes#376]
In service-authorization/uat-deployment.yaml in reportportal-24.1.0 branch, line 187 is incorrect and should be removed.

`
     tolerations:

{{- with .Values.tolerations }}
      tolerations: 
{{- toYaml . | nindent 8 }}
`

**Comment by raikbitters** [comment]
https://github.com/reportportal/kubernetes/pull/377

**Comment by Pink-Bumblebee** [comment]
@ctsscott , thank you for highlight.
