### ISSUE TITLE
List of problems with helm chart.

### ISSUE THREAD

**Issue by doertedev** [reportportal/kubernetes#4]
Hi.

The sense of a helm chart is to have the k8s specs completely free of default values, so a user can overwrite them in the values.yaml as she sees fit.

Furthermore it makes no sense to let a user overwrite to her own registry but tell her [to use your specific image](https://github.com/reportportal/k8s/blob/master/templates/elasticsearch-statefulset.yaml#L18). If certain changes are required to run a ES that is fit for RP are needed, i'd either create a sidecar or schedule a k8s-job for this. The customers you'll want to target most likely have their preferred ES version and that way they could make it run. Dictating the specific image leads nowhere. Another one that comes to mind is the [data directory path](https://github.com/reportportal/k8s/blob/master/templates/elasticsearch-statefulset.yaml#L22). 

RE: #3 - https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml#L147 << storageClass should be defined and listed as "-"

When storageClass is defined and equals to gp2 or something related to cloud envs, then PVC is used and not PV and there is no need for `volumeNames`.

If storageClass is not default (e.g. "gp2" or whatever), then `hostPath` is not needed.

Applying ingress as it and creating A record in DNS will not resolve addresses in values.yaml. It should be changed to NodePort, not ClusterIP. ClusterIP is used when you're using minikube because everything is NATed. This does not even remotely cover cloud environments.

**Comment by DzmitryHumianiuk** [comment]
@doertedev could you send us PR?
we can review it.

**Comment by doertedev** [comment]
Extremely short on resources and trapped in hiring and other shenannigans r/n. Maybe @dusansusic can at some point throw an eye on this.

**Comment by avarabyeu** [comment]
DB now installed via official Postgres helm chart so the issue is fixed
