### ISSUE TITLE
[Feature] Add replica count support to all deployments

### ISSUE THREAD

**Issue by tomikonio** [reportportal/kubernetes#405]
Hi,
Most of the deployments, other than the API one, have a hard-coded replica count.
i.e. -  the UI deployment: https://github.com/reportportal/kubernetes/blob/8ff681f52585e9340c3576ee7531658e07ecb4a9/reportportal/templates/service-ui/ui-deployment.yaml#L7

Can we add support for specifying the replica count in the various deployments?
What about the statefulsets?
I can create a PR if this does not have implications.

Thanks.

**Comment by hlebkanonik** [comment]
Done for services that support replicas greater than 1
