### ISSUE TITLE
[BUG] Helm chart versioning - constant terraform diff

### ISSUE THREAD

**Issue by gothrek22** [reportportal/kubernetes#408]
Hi,

it seems that due to not following consistent versioning, when it comes to bigger releases, i.e. releasing 24.1 instead of 24.1.0. If someones uses Terraform with Helm to manage the deployment, it will cause a persistent diff to appear, because the rendered helm manifest has version 24.1 vs the one on the cluster will have the latest version from the 24.1.x tree (at the moment it is 24.1.2).

Please fix your approach to versioning chart to be consistent across releases.

**Comment by Pink-Bumblebee** [comment]
@gothrek22 , thank you for your propose! We will discuss internally how to do it and who will be responsible.

**Comment by hlebkanonik** [comment]
#424 Chart version updated
