### ISSUE TITLE
[Bug] RP_ELASTICSEARCH_HOST variable in service-api causes issues

### ISSUE THREAD

**Issue by dracut5** [reportportal/kubernetes#409]
Hi,

We have recently updated helm chart from `23.2.0` to `24.1.2` version: everything went good, except we noticed in a while that [To investigate](https://reportportal.io/docs/analysis/SearchForTheSimilarToInvestigateItems/) feature stopped working.
We have run the old version alongside and discovered that it is working on the same test case. After deep investigation we found the errors in service-api logs

```
2024-07-31 13:42:09.322 ERROR 1 --- [nio-8585-exec-9] c.e.t.r.dao.custom.ElasticSearchClient   : Search error logs-reportportal-17 Terms: {"id":[42826]} Message: 401 Unauthorized: [no body]
2024-07-31 13:42:09.329 ERROR 1 --- [io-8585-exec-10] c.e.t.r.dao.custom.ElasticSearchClient   : Search error logs-reportportal-17 Terms: {"id":[42826]} Message: 401 Unauthorized: [no body]
2024-07-31 13:45:29.305 ERROR 1 --- [nio-8585-exec-2] c.e.t.r.dao.custom.ElasticSearchClient   : Search error logs-reportportal-17 Terms: {"id":[42827]} Message: 401 Unauthorized: [no body]
```

We have checked the changes and the ENV var related to ElasticSearch configuration has been changed for API service
https://github.com/reportportal/kubernetes/blob/reportportal-24.1.2/reportportal/templates/service-api/api-deployment.yaml#L87

But we couldn't find any creds for ES in the template like they exist for `service-jobs`
https://github.com/reportportal/kubernetes/blob/reportportal-24.1.2/reportportal/templates/service-jobs/jobs-deployment.yaml#L68

When we renamed back the mentioned ENV var to `RP_ELASTICSEARCHLOGMESSAGE_HOST`, the feature started working again and errors are gone.

Could you, please, take a look on that? It looks like, `service-api` is expecting such new var and change its behavior correspondently.

Many thanks!

**Comment by Pink-Bumblebee** [comment]
@dracut5 , we've posted answer to this issue in Slack. Anyway, I am copying it here:

>  correct variables for elastic search in api
> 
> > RP_ELASTICSEARCH_HOST
> > RP_ELASTICSEARCH_USERNAME
> > RP_ELASTICSEARCH_PASSWORD
> 
> just fyi: In future release we plan to rename them to support opensearch
> > RP_SEARCHENGINE_HOST
> > RP_SEARCHENGINE_HOST
> > RP_SEARCHENGINE_HOST

This answer is related to release v24.1 (24.1.x)

**Comment by dracut5** [comment]
Thank you @Pink-Bumblebee.

Sorry, I just didn't understand from the answer whether it is helm chart template issue or `service-api` internal error.
Decided that it would be good idea to open the issue here to help other people who are looking for the solution to make `To investigate` feature work again.

Now I see that `RP_ELASTICSEARCH_USERNAME` and `RP_ELASTICSEARCH_PASSWORD` should be added to the corresponded template and DEV team knows about that.

Great, thanks again!

**Comment by dracut5** [comment]
Hi, 
@hlebkanonik thank you for the answer!
I suppose you meant not `instead` of PostgreSQL but additionally to, correct?
Does it mean that migration to OpenSearch/ElasticSearch engine is deprecated/postponed?

**Comment by hlebkanonik** [comment]
Yes, I meant in addition to PostgreSQL, rather than replacing it. 

The migration to OpenSearch/ElasticSearch is currently postponed as we explore alternative options.
