### ISSUE TITLE
[Question] 24.1.3 Queues Per Pod Changes

### ISSUE THREAD

**Issue by tomikonio** [reportportal/kubernetes#415]
Hi,
In `24.1.3`, changes were made to the `serviceapi.queues` parameter:
https://github.com/reportportal/kubernetes/compare/reportportal-24.1.2...reportportal-24.1.3#diff-c554617a65c1ad51602ac8780bbe79db48ddcc7b00106d755361a16301b571ecL135
![image](https://github.com/user-attachments/assets/dcfef04c-2aca-4b36-b633-f9552adcd068)
The changes were introduced in this PR -> https://github.com/reportportal/kubernetes/pull/403

There is no more control over the `perPodNumber` amount.
Is it recommended for the total queue number to be equal to the per-pod number now? (in case we have more than one API pod)

**Comment by hlebkanonik** [comment]
Hi! The settings for the new release have leaked from develop to a minor helm chart update. I have re-released the hotfix for version [23.1.3](https://github.com/reportportal/kubernetes/releases/tag/reportportal-24.1.3). 

Please get the latest chart information by running `helm repo update` or cloning the [master branch](https://github.com/reportportal/kubernetes/tree/master).

Regarding the changes to the queues, they will be included in the release notes soon. I appreciate your interest!
