### ISSUE TITLE
Error upgrading reportportal helm chart from 24.1.0 to 24.1.5: multiple invalid resource names

### ISSUE THREAD

**Issue by Uritassa** [reportportal/kubernetes#421]
Hi

When attempting to upgrade the reportportal helm chart from version 24.1.0 to 24.1.5, I encountered an error. The error message indicates that multiple resources have invalid names.

Here is the full error message:

one or more objects failed to apply, reason:... (see below for full error message)
		

The error message lists multiple resources with invalid names, including:

    Service "-api"
    Service "-index"
    Service "-metrics-gatherer"
    Service "-analyzer"
    Service "-analyzer-train"
    Service "-jobs"
    Service "-ui"
    Deployment.apps "-api"
    Deployment.apps "-index"
    Deployment.apps "-metrics-gatherer"
    Deployment.apps "-analyzer"
    Deployment.apps "-analyzer-train"
    Deployment.apps "-jobs"
    Deployment.apps "-ui"
    Job.batch "-migrations"

The error message indicates that the names of these resources are invalid because they do not meet the requirements for DNS-1035 labels or lowercase RFC 1123 subdomains.

I also tried customizing the hooks values to disable the pre-upgrade hook, but this did not resolve the issue:

hooks:
  enabled: true
  preUpgrade:
    enabled: false
  test:
    enabled: false
		

Steps to reproduce:

    Upgrade reportportal helm chart from 24.1.0 to 24.1.5.

Expected behavior:

The upgrade should complete successfully without errors.

Actual behavior:

The upgrade fails with the error message above.

**Comment by raikbitters** [comment]
@Uritassa hi. Could you provide a helm command that you use for upgrading?

**Comment by Uritassa** [comment]
Hi @raikbitters, I actually used ArgoCD to upgrade the reportportal helm chart, not a direct helm command.

I'm running all dependencies (including PostgreSQL) separately
and using postgresql v16.

I tried upgrading to 24.1.3, but unfortunately, I encountered the same error, the error message remains the same. let me know if there's anything else I can try.

**Comment by Uritassa** [comment]
UPDATE:

I completely removed reportportal from Argocd and deployed reportportal latest version from scratch using the following helm command:

helm install reportportal reportportal/reportportal -f values.yaml -n reportportal
		

However, I'm still facing the same issue with the same errors:

Error: INSTALLATION FAILED: 18 errors occurred:
        * Service "-analyzer" is invalid: [metadata.name: Invalid value: "-analyzer": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g.'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'), spec.selector: Invalid value: "-analyzer": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')] 
		

It seems that the issue is not related to the upgrade process, but rather with the chart itself. I would appreciate any help in resolving this issue.

**Comment by raikbitters** [comment]
@Uritassa Hi, why do you use the "-f value.yaml"? Do you have a different Value file?
Also, could you write a Helm version?

I successfully tested the upgrade command, and it works for me with helm version "3.15.4"
Could you try this to upgrade:

```bash
helm upgrade reportportal \
  reportportal/reportportal \
  --version 24.1.3
```

or install using this:

```bash
export SUPERADMIN_PASSWORD=your_password

helm install reportportal \
  reportportal/reportportal \
  --set uat.superadminInitPasswd.password=${SUPERADMIN_PASSWORD}
```

**Comment by Uritassa** [comment]
I removed this line from my values.
fullnameOverride: "reportportal"
now its working
