### ISSUE TITLE
Support setting affinity rules

### ISSUE THREAD

**Issue by fornhunkle** [reportportal/kubernetes#432]
Recent updates allow setting `replicaCount` for deployments but the templates don't support setting affinity rules. In my case I want the pods running on different nodes.

Is this something you would consider adding?

If so, I could have a go at creating a PR for it.

Something along the lines of this for each deployment that can set replicas:

```
spec:
  template:
    spec:
      {{- with .Values.uat.affinity }}
      affinity: {{ toYaml . | indent 6 }}
      {{- end }}
```

**Comment by hlebkanonik** [comment]
Hello! This is an open-source product, and a PR would be helpful. Thank you in advance!

**Comment by maybeagarden** [comment]
Hey @hlebkanonik I've raised a PR for this (different account than the one I originally commented with)

The changes seem to be doing what I want when playing around with it locally but I don't have much experience with helm so please check it closely

https://github.com/reportportal/kubernetes/pull/436

**Comment by hlebkanonik** [comment]
Hi! PR #436 has been merged into `develop`. The upcoming release of ReportPortal will include this change.

**Comment by maybeagarden** [comment]
awesome, thank you!

**Comment by CalebHenshaw** [comment]
When is the next release scheduled?

**Comment by hlebkanonik** [comment]
@CalebHenshaw, Jan 25
