### ISSUE TITLE
Can't see the attachments

### ISSUE THREAD

**Issue by jonacarvalheiro** [reportportal/kubernetes#50]
After a run with attachments, 
![image](https://user-images.githubusercontent.com/11489396/63874308-36617480-c9b9-11e9-895f-d3492c3498b1.png)

When I access the log page with the attachments, this message/error appear:

{"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.SQLGrammarException: could not extract ResultSet]"}

And I'm getting this error for each attachment on the console:
{"errorCode":4001,"message":"Incorrect Request. Unable to find file"}

After I checked the postgresql logs and when I'm trying to access the page with the atachments I'm getting this log:

2019-08-28 13:21:05.113 GMT [2678] ERROR:  syntax error at or near ")" at character 76
2019-08-28 13:21:05.113 GMT [2678] STATEMENT:  SELECT * FROM test_item ti WHERE ti.unique_id IN ($1) AND ti.launch_id IN ()

I think this statement is not really valid. Could you check this out?

**Comment by avarabyeu** [comment]
@jonacarvalheiro could please specify exact version of API service that you use?

**Comment by AlehB** [comment]
Hi @jonacarvalheiro,
Could you please specify the version of api service that you use or we will close the issue?

**Comment by evjlobanova** [comment]
Due to no response, we are closing this issue
