### ISSUE TITLE
Service annotation of analyzer-service

### ISSUE THREAD

**Issue by prathameshnyt** [reportportal/kubernetes#65]
Thank you for the nice templates. 

Looks like it's a typo. Service annotation is UAT instead of the analyzer.

https://github.com/reportportal/kubernetes/blob/2093061a99d2661070e7807fddc3ccadd6217851/reportportal/v5/templates/analyzer-service.yaml#L7

Can you please check?

**Comment by AlehB** [comment]
Hi @prathameshnyt,

Thank you for your note!
This part of the code is not required anymore since analyzer does not have http interface

I will clean it up

Best Regards,
Aleh

**Comment by AlehB** [comment]
The code has been updated

**Comment by prathameshnyt** [comment]
Thanks, @AlehB.
