### ISSUE TITLE
Error: error converting YAML to JSON: yaml: line 12: did not find expected key

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/kubernetes#80]
while Performing Instalation of Reportportal.io in kubernetes

Deploy the chart:

helm install ./<project folder>`

getting error As below

![Capture](https://user-images.githubusercontent.com/58975085/73052589-7ca8fa00-3eab-11ea-940d-58838922d60b.PNG)

**Comment by dharma-keyutech** [comment]
> while Performing Instalation of Reportportal.io in kubernetes
> 
> Deploy the chart:
> 
> helm install ./`
> 
> getting error As below
> 
> ![Capture](https://user-images.githubusercontent.com/58975085/73052589-7ca8fa00-3eab-11ea-940d-58838922d60b.PNG)

Using this Chart.yaml


https://github.com/reportportal/kubernetes/blob/master/reportportal/v5/Chart.yaml

**Comment by AlehB** [comment]
Hi @dharma-keyutech ,

The Chart.yaml is valid, just retested.

Please follow the guide https://github.com/reportportal/kubernetes/tree/master/reportportal/v5 exactly

There no 'helm install ./',
but
'helm package ./reportportal/'
and
'helm install --name <reportportal_chart_name> --set postgresql.SecretName=<db_chart_name>-postgresql,rabbitmq.SecretName=<rabbitmq_chart_name>-rabbitmq-ha ./reportportal-5.0-SNAPSHOT.tgz' (for Helm db in this example)

Best,
Aleh

**Comment by dharma-keyutech** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/58975085/73082436-7b012580-3eef-11ea-81e1-e44af11a8405.png)

**Comment by AlehB** [comment]
Of course, because you are inside this directory

Should be one level above

**Comment by dharma-keyutech** [comment]
Thank you

**Comment by dharma-keyutech** [comment]
That's working fine 

Later getting an Error as shown in below


Error: found in requirements.yaml, but missing in charts/ directory: postgresql, rabbitmq-ha, elasticsearch, minio
