### ISSUE TITLE
Getting the Issues while instaling reportportal in Kubernates

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/kubernetes#86]
Auto Scaling is also Added to the cluster

![image](https://user-images.githubusercontent.com/58975085/73589617-75629b80-44fe-11ea-8507-a0f51bc3fb6f.png)

**Comment by dharma-keyutech** [comment]
Image source for error exit code 1


![image](https://user-images.githubusercontent.com/58975085/73589680-95468f00-44ff-11ea-9f79-fa4dcfb25b89.png)

**Comment by HardNorth** [comment]
Well, I see an issue with elasticsearch deployment. That will block your analyzer startup. Please read our documentation carefully and try to reinstall it: https://github.com/reportportal/kubernetes/tree/master/reportportal/v5#4-elasticsearch-installation

Another thing I see that your migration job didn't start up. Please check a pod logs for any errors, it's impossible to say anything without them.

**Comment by dharma-keyutech** [comment]
getitng issue with elasticsearch deployment. 


![image](https://user-images.githubusercontent.com/58975085/73632610-33faf900-4682-11ea-90ef-013b6013f837.png)

**Comment by AlehB** [comment]
Please describe the elasticsearch pods (kubectl descrbe ..) to see if there anything blocks them from running
At the moment it is not in ready state (0/1)

Make sure all neccessary pods are in "Running" state and the migrations was completed. You can use 'describe' and 'logs' to investigate

**Comment by dharma-keyutech** [comment]
How to resolve it


![image](https://user-images.githubusercontent.com/58975085/73722444-81dc3380-474c-11ea-9153-248b2eecf67f.png)

**Comment by AlehB** [comment]
Not enough info.
![image](https://user-images.githubusercontent.com/2253605/73722598-ec36a900-4737-11ea-9ea1-7d7de1700e8a.png)

**Comment by dharma-keyutech** [comment]
How we can find warnings and errors 


![image](https://user-images.githubusercontent.com/58975085/73734515-c3c4a400-4763-11ea-9a0b-32f4560f289c.png)

**Comment by AlehB** [comment]
As I mentioned above, you can use kubectl describe pod <pod_name> and kubectl logs. This is basic Kubernetes knowledge.
Since you are using GKE, you can also click on "Container logs" and find the issue

e.g.
![image](https://user-images.githubusercontent.com/2253605/73738256-34b08f80-4755-11ea-9199-9279fba14093.png)

**Comment by dharma-keyutech** [comment]
in container log 

![image](https://user-images.githubusercontent.com/58975085/73739329-01c5c600-476c-11ea-85e0-a7a728631563.png)

**Comment by AlehB** [comment]
That means you container is not running. Use 'kubectl describe pod <pod_name>'

Since we do not consult on basic Kubernetes technology knowledge, please contact your DevOps enginner and use our paid support.

In case you find any specific related ReportPortal issue in your logs, contact us again

**Comment by dharma-keyutech** [comment]
After Running this command  : kubectl describe pod reportportal-api-6ddb768799

ERROR : _

Name:           reportportal-api-6ddb768799-5m2mw
Namespace:      default
Priority:       0
Node:           gke-dev-cluster-1-default-pool-d8cd7b81-jc0b/10.128.0.22
Start Time:     Tue, 04 Feb 2020 16:10:10 +0530
Labels:         component=reportportal-api
                pod-template-hash=6ddb768799
Annotations:    <none>
Status:         Running
IP:             10.24.0.8
Controlled By:  ReplicaSet/reportportal-api-6ddb768799
Containers:
  api:
    Container ID:   docker://6da4a42cde7e4c67ad87023ac43a08a2c78792667be4544e5d492c56aa631a24
    Image:          reportportal/service-api:5.0.0
    Image ID:       docker-pullable://reportportal/service-api@sha256:5f792f47a568024bc06b535c78e750d7ad13c369e6db6f5382051c5d86eca407
    Port:           8585/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
Reason:       Error
      Exit Code:    1
      Started:      Tue, 04 Feb 2020 16:40:44 +0530
      Finished:     Tue, 04 Feb 2020 16:41:50 +0530
    Ready:          False
    Restart Count:  9
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      500m
      memory:   1Gi
    Readiness:  http-get http://:8585/health delay=30s timeout=3s period=20s #success=1 #failure=20
    Environment:
      LOGGING_LEVEL_ORG_HIBERNATE_SQL:  info
      RP_REQUESTLOGGING:                false
      RP_AMQP_QUEUES:                   10
      RP_AMQP_QUEUESPERPOD:             10
      JAVA_OPTS:                        -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
      RP_AMQP_HOST:                     postgrsql-rabbitmq-ha.default.svc.cluster.local
      RP_AMQP_PORT:                     5672
      RP_AMQP_USER:                     rabbitmq
      RP_AMQP_PASS:                     <set to the key 'rabbitmq-password' in secret 'postgrsql-rabbitmq-ha'>  Optional: false
      RP_AMQP_APIPORT:                  15672
      RP_AMQP_APIUSER:                  rabbitmq
      RP_AMQP_APIPASS:                  <set to the key 'rabbitmq-password' in secret 'postgrsql-rabbitmq-ha'>  Optional: false
      RP_DB_HOST:                       postgresql-postgresql.default.svc.cluster.local
      RP_DB_PORT:                       5432
      RP_DB_USER:                       rpuser
      RP_DB_PASS:                       <set to the key 'postgresql-password' in secret 'postgresql-postgresql'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qw4cp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
PodScheduled      True
Volumes:
  default-token-qw4cp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qw4cp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                                   Message
  ----     ------     ----                  ----                                                   -------
  Normal   Scheduled  32m                   default-scheduler                                      Successfully assigned default/reportportal-api-6ddb768799-5m2mw to gke-dev-cluster-1-default-pool-d8cd7b81-jc0b
  Normal   Pulled     28m (x4 over 32m)     kubelet, gke-dev-cluster-1-default-pool-d8cd7b81-jc0b  Container image "reportportal/service-api:5.0.0" already present on machine
  Normal   Created    28m (x4 over 32m)     kubelet, gke-dev-cluster-1-default-pool-d8cd7b81-jc0b  Created container api
  Normal   Started    28m (x4 over 32m)     kubelet, gke-dev-cluster-1-default-pool-d8cd7b81-jc0b  Started container api
  Warning  Unhealthy  7m24s (x16 over 32m)  kubelet, gke-dev-cluster-1-default-pool-d8cd7b81-jc0b  Readiness probe failed: Get http://10.24.0.8:8585/health: dial tcp 10.24.0.8:8585: connect: connection refused
  Warning  BackOff    2m36s (x95 over 30m)  kubelet, gke-dev-cluster-1-default-pool-d8cd7b81-jc0b  Back-off restarting failed container

**Comment by AlehB** [comment]
First you need to make sure that all RP requirements (RabbitMQ, ElasticSearch, PostgreSQL and Minio) are up and running. Start from ES. because it is not ready.

Then check why migrations exit with code 1 (e.g. cannot establish connection your database, no permissions?)

**Comment by dharma-keyutech** [comment]
Values.yaml 

i gave all permisions



## String to partially override reportportal.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override reportportal.fullname template
##
# fullnameOverride:

serviceindex:
  name: index
  repository: reportportal/service-index
  tag: 5.0.5
  pullPolicy: Always
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

uat:
  repository: reportportal/service-authorization
  name: uat
  tag: 5.0.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400

serviceui:
  repository: reportportal/service-ui
  tag: 5.0.0
  name: ui
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

serviceapi:
  repository: reportportal/service-api
  tag: 5.0.0
  name: api
  pullPolicy: Always
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 20
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  jvmArgs: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp "

migrations:
  repository: reportportal/migrations
  tag: 5.0.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceanalyzer:
  repository: reportportal/service-analyzer
  tag: 5.0.0
  name: analyzer
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

rabbitmq:
  SecretName: "postgrsql-rabbitmq-ha"
  installdep:
    enable: true
  endpoint:
    cloudservice: false
    address: postgrsql-rabbitmq-ha.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq
    password: 12345

postgresql:
  SecretName: "postgresql-postgresql"
  installdep:
    enable: true
  endpoint:
    cloudservice: false
    address: postgresql-postgresql.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password: 12345

elasticsearch:
  installdep:
    enable: false
  endpoint:
    cloudservice: false
    address: elasticsearch-master
    port: 9200

minio:
  enabled: false
  installdep:
    enable: false
  endpoint: http://minio.default.svc.cluster.local:9000
  region:
  accesskey: Admin
  secretkey: admin

# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - reportportal.k8.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "2000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1000"

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true


# RBAC is required for service-index in order to collect status/info over all services
rbac:
  create: true
  serviceAccount:
      create: true
      name: reportportal

rp:
  infoEndpoint: "/info"
  healthEndpoint: "/health"

**Comment by AlehB** [comment]
Dear @dharma-keyutech ,

Please read the guide carefully.

**Comment by AlehB** [comment]
Ex. for db permission
https://github.com/reportportal/kubernetes/tree/master/reportportal/v5#6-postgresql-installation
6.1.2

**Comment by AlehB** [comment]
Anyway, you need to fix your ES installation first.
Then check migrations logs / describe the pod

**Comment by AlehB** [comment]
P.S. I'm not sure if db password "12345" suits the minimum requirements.
P.S.S. Since you are using PostgreSQL Helm chart there should not be any password in values.yaml.

Once again, please go thourgh guide step by step

**Comment by dharma-keyutech** [comment]
ES Error was resolved 
here is my postgresql values in values.Yaml file 
![image](https://user-images.githubusercontent.com/58975085/73746278-d696a300-477a-11ea-903f-2b3e6dd10720.png)

**Comment by dharma-keyutech** [comment]
i make rpuser as a super user also

**Comment by AlehB** [comment]
Now you can check the migrations logs / describe the pod to inverstigate why it exit with code 1

**Comment by dharma-keyutech** [comment]
Here are the migrations Errors 
![image](https://user-images.githubusercontent.com/58975085/73748086-c08ae180-477e-11ea-8768-19d265cd20c8.png)


--------------------- 
After executing below command 
kubectl logs reportportal-migrations-2vr87

![image](https://user-images.githubusercontent.com/58975085/73748219-f7f98e00-477e-11ea-9228-c7e1d5a36601.png)

**Comment by AlehB** [comment]
You have passed some wrong value 'postgresql-postgresql.default' to the Helm chart.

Make sure that

a) You installed PostgreSQL Helm chart correctly.

_e.g.
helm install --name postgresqltest --set postgresqlUsername=rpuser,postgresqlPassword=Admin,postgresqlDatabase=reportportal ./reportportal/charts/postgresql-3.9.1.tgz_

b) Then redeploy the RP Helm chart correctly

_e.g.
helm install --name reportportal --set postgresql.SecretName=postgresqltest-postgresql,rabbitmq.SecretName=<rabbitmq_chart_name>-rabbitmq-ha ./reportportal-5.tgz_

**Comment by dharma-keyutech** [comment]
> helm install --name postgresqltest --set postgresqlUsername=rpuser,postgresqlPassword=Admin,postgresqlDatabase=reportportal ./reportportal/charts/postgresql-3.9.1.tgz

i have used that command only to install

helm install --name postgresql --set postgresqlUsername=rpuser,postgresqlPassword=Admin,postgresqlDatabase=reportportal ./reportportal/charts/postgresql-3.9.1.tgz

**Comment by AlehB** [comment]
rabbitmq.SecretName=<rabbitmq_chart_name>-rabbitmq-ha, not rabbitmq.SecretName=**postgrsql**-rabbitmq-ha

The Helm chart has been tested in GKE with no issue. Please read the guide again and redeploy everything very carefully.
The issue is closed

**Comment by dharma-keyutech** [comment]
helm install --name reportportal --set postgresql.SecretName=postgresql-postgresql,rabbitmq.SecretName=rabbitmq-rabbitmq-ha ./reportportal-5.tgz

--------------------rabbitmq Values in Values.yaml--------------------
![image](https://user-images.githubusercontent.com/58975085/73756372-73623c00-478d-11ea-8805-4f77b4815121.png)

**Comment by AlehB** [comment]
Once again, as I mentioned above
![image](https://user-images.githubusercontent.com/2253605/73758579-d5b24100-477b-11ea-862e-f0cc92e0b26d.png)

postgrsql (postgresql?) is **not** **rabbitmq** chart name

Solution:

Documentation (highly recommend reading carefully)
https://github.com/reportportal/kubernetes/tree/master/reportportal/v5

GKE
https://cloud.google.com/kubernetes-engine

Helm
https://helm.sh

Kubernetes
https://kubernetes.io

Best Regards

**Comment by dharma-keyutech** [comment]
Thank you for your support & patience 

Will work on it and update you
