### ISSUE TITLE
RabbitMQ "analyzer" vhost not automatically created or documented

### ISSUE THREAD

**Issue by LittleColin** [reportportal/kubernetes#94]
I found that the reportportal-analyzer would not start up and reported:

Exception (403) Reason: "no access to this vhost"

The error above does not include the name of the vhost which isn't in configuration so had to dive into the code which shows it is hard-coded as "analyzer":

https://github.com/reportportal/service-analyzer/blob/master/main.go#L131

Manually creating this vhost in the RabbitMQ portal worked around the issue. 

RabbitMQ version 3.7.8

Perhaps this needs to be documented or the vhost automatically created?
https://github.com/reportportal/kubernetes/tree/master/reportportal/v5#5-rabbitmq-installation

**Comment by AlehB** [comment]
Hi @LittleColin ,

**Comment by AlehB** [comment]
Hi @LittleColin ,

This must be created automatically. @pbortnik , is there any changes in api? Looks like it is not creation automatically anymore.

Could you please tell me which cloud you are using?

Best Regards,
Aleh

**Comment by LittleColin** [comment]
The API is from docker image: reportportal/service-api:5.0.0 on an Azure AKS cluster.

**Comment by AlehB** [comment]
Hi @LittleColin ,

I have tested the application with API service from reportportal/service-api:5.0.0 on

- Docker
- AWS EKS
- Azure AKS

vhost "analyzer" creates automatically with all necessary permissions

RabbitMQ version 3.7.23 from https://github.com/reportportal/kubernetes/blob/master/reportportal/v5/requirements.yaml#L7

**Comment by LittleColin** [comment]
I've also reinstalled and cannot reproduce this issue - I'm thinking something must have failed part way through to have left it in this odd state the first time. Thanks for investigating @AlehB .
