### ISSUE TITLE
Migrations do not report failure

### ISSUE THREAD

**Issue by LittleColin** [reportportal/kubernetes#95]
The logs for the migrations show:

`timeout: unrecognized option: t
BusyBox v1.31.1 () multi-call binary.

Usage: timeout [-s SIG] SECS PROG ARGS

Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
Default SIG: TERM.
wait-for-it.sh: timeout occurred after waiting 15 seconds for report01-psql-postgresql.report01.svc.cluster.local:5432
no change`

However this doesn't cause the migrations pod to go into error state in Kubernetes (just happened to notice while digging around)

**Comment by LittleColin** [comment]
Note there is a secondary and more important issue in that the migrations do not work due to a breaking change in busybox which removed the -t argument - this means the docker container reportportal/migrations:5.0.0 is currently broken:

https://github.com/mirror/busybox/commit/c9720a761e88e83265b4d75808533cdfbc66075b

**Comment by AlehB** [comment]
We are currently using migrations:5.0.0 in AWS EKS and Azure, and it works pretty well

The logs should be
wait-for-it.sh: waiting 15 seconds for <db_address>:5432
wait-for-it.sh: <db_address>:5432 is available after 0 seconds
no change

And pod in
0/1     Completed

**Comment by LittleColin** [comment]
Perhaps your image could have been cached?

Try:
docker run -it --entrypoint /bin/sh reportportal/migrations:5.0.0 
Then at the prompt:
./wait-for-it.sh localhost:80

Do your pod logs show you are using BusyBox v1.31.1 for migrations?

**Comment by AlehB** [comment]
There is pullPolicy: Always

Yes, we have "timeout: unrecognized option: t" on AWS EKS, but it does not interfere with its work
Migrations works in your env as well

But anyway I have addressed this problem to the dev team

**Comment by LittleColin** [comment]
Great, thanks for the fast reply.

**Comment by AlehB** [comment]
@pbortnik , could you please take a look?
should we update the migrations container?

**Comment by zozo6015** [comment]
I am trying to install reportportal on kubernetes and I get the same errors as above only difference that it ends up with an error as showed:

```
wait-for-it.sh: waiting 15 seconds for postgresql:5432
wait-for-it.sh: postgresql:5432 is available after 0 seconds
error: Dirty database version 0. Fix and force version.
```

I am assuming it is a postgresql version issue thereore I am wodering what version of postgresql is supported?

**Comment by shree1988** [comment]
> I am trying to install reportportal on kubernetes and I get the same errors as above only difference that it ends up with an error as showed:
> 
> ```
> wait-for-it.sh: waiting 15 seconds for postgresql:5432
> wait-for-it.sh: postgresql:5432 is available after 0 seconds
> error: Dirty database version 0. Fix and force version.
> ```
> 
> I am assuming it is a postgresql version issue thereore I am wodering what version of postgresql is supported?

Were you able to resolve the issue? I am facing the same issue
